/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { AirAvailabilityReturnFlightController } from '../src';
import { testClient } from './testClient.js';
import { makeApiCall } from './testHelper.js';

describe('AirAvailabilityReturnFlightController', () => {
  let controller : AirAvailabilityReturnFlightController;

  beforeAll(() => {
    controller = new AirAvailabilityReturnFlightController(testClient);
  });

  it('should Test Availability', async () => {
    const authorization = 'Signature {{signature}}';

    const body = '{\n	"api_key": "{{ASB_API_KEY}}",\n	"timestamp": "{{timestamp}}",\n	"nonce": "{{nonce}}",\n	"locale": "en_US",\n	"customer_ip": "127.0.0.1",\n	"session_id": "{{session_id}}",\n	"user_agent": "curl/7.64.0",\n	"system": "aft",\n	\n	"configuration_id": {{configuration_id}},\n	"origin_destinations": [\n		{\n            "departure_date": "{{departure_date_1}}",\n            "departure_location": {\n                "location_code": "{{departure_1}}",\n                "location_type": "airport"\n            },\n            "arrival_location": {\n                "location_code": "{{arrival_1}}",\n                "location_type": "airport"\n            },\n            "direct_only": {{direct_only}}\n		},\n        {\n            "departure_date": "{{departure_date_2}}",\n            "departure_location": {\n                "location_code": "{{departure_2}}",\n                "location_type": "airport"\n            },\n            "arrival_location": {\n                "location_code": "{{arrival_2}}",\n                "location_type": "airport"\n            },\n            "direct_only": {{direct_only}}\n		}\n	]\n}';

    const response = await makeApiCall(
      () => controller.availability(authorization, body)
    );

    expect(response.statusCode).toBe(200);
  });
});
