/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  AircompleteVerificationRequest,
  AirController,
  AirdocumentsIssueRequest,
  AirretrieveReservationsListRequest,
} from '../src';
import { testClient } from './testClient.js';
import { makeApiCall } from './testHelper.js';

describe('AirController', () => {
  let controller : AirController;

  beforeAll(() => {
    controller = new AirController(testClient);
  });

  it('should Test Destination_lookup', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const system = 'aft';

    const term = 'lond';

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.destinationLookup(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        system,
        term,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Documents_issue', async () => {
    const authorization = 'Signature {{signature}}';

    const body: AirdocumentsIssueRequest = {
      apiKey: '{{ASB_API_KEY}}',
      timestamp: '{{timestamp}}',
      nonce: '{{nonce}}',
      locale: 'en_US',
      customerIp: '127.0.0.1',
      sessionId: '{{session_id}}',
      userAgent: 'curl/7.64.0',
      system: 'aft',
      bookingUid: '63a36d2c2d4d55f488e097c2',
      issueTickets: true,
      issueEmds: true,
    };

    const response = await makeApiCall(
      () => controller.documentsIssue(authorization, body)
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Complete_verification', async () => {
    const authorization = 'Signature {{signature}}';

    const body: AircompleteVerificationRequest = {
      apiKey: '{{ASB_API_KEY}}',
      timestamp: '{{timestamp}}',
      nonce: '{{nonce}}',
      locale: 'en_US',
      customerIp: '127.0.0.1',
      sessionId: '{{session_id}}',
      userAgent: 'curl/7.64.0',
      system: 'aft',
      verificationId: 'SdclrQ5x8BumYVOXbwmJ5tIYKNG5sUe0unafapdxpasdRfbFdjM40g==',
    };

    const response = await makeApiCall(
      () => controller.completeVerification(authorization, body)
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Retrieve_reservations_list', async () => {
    const authorization = 'Signature {{signature}}';

    const body: AirretrieveReservationsListRequest = {
      apiKey: '{{ASB_API_KEY}}',
      timestamp: '{{timestamp}}',
      nonce: '{{nonce}}',
      locale: 'en_US',
      customerIp: '127.0.0.1',
      sessionId: '{{session_id}}',
      userAgent: 'curl/7.64.0',
      system: 'aft',
      travelerEmail: 'rkaydanowski+hcat@bcdtriptech.com',
      limit: 10,
      offset: 11,
      currency: 'UAH',
    };

    const response = await makeApiCall(
      () => controller.retrieveReservationsList(authorization, body)
    );

    expect(response.statusCode).toBe(200);
  });
});
