/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { AirFareSearchOptionalServicesController } from '../src';
import { testClient } from './testClient.js';
import { makeApiCall } from './testHelper.js';

describe('AirFareSearchOptionalServicesController', () => {
  let controller : AirFareSearchOptionalServicesController;

  beforeAll(() => {
    controller = new AirFareSearchOptionalServicesController(testClient);
  });

  it('should Test Get_checkout_data', async () => {
    const authorization = 'Signature {{signature}}';

    const body = '{\n	"api_key": "{{ASB_API_KEY}}",\n	"timestamp": "{{timestamp}}",\n	"nonce": "{{nonce}}",\n	"locale": "en_US",\n	"customer_ip": "127.0.0.1",\n	"session_id": "{{session_id}}",\n	"user_agent": "curl/7.64.0",\n	"system": "aft",\n	\n	"configuration_id": {{configuration_id}},\n    "fare_group_key": "{{fare_group_key}}",\n    "tspm_traveler_id": "{{tspm_traveler_id}}",\n    "tspm_company_id": "{{tspm_company_id}}"\n}';

    const response = await makeApiCall(
      () => controller.getCheckoutData(authorization, body)
    );

    expect(response.statusCode).toBe(200);
  });
});
