/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { AirFareSearchSelectSeatController } from '../src';
import { testClient } from './testClient.js';
import { makeApiCall } from './testHelper.js';

describe('AirFareSearchSelectSeatController', () => {
  let controller : AirFareSearchSelectSeatController;

  beforeAll(() => {
    controller = new AirFareSearchSelectSeatController(testClient);
  });

  it('should Test Fare_rules', async () => {
    const authorization = 'Signature {{signature}}';

    const body = '{\n	"api_key": "{{ASB_API_KEY}}",\n	"timestamp": "{{timestamp}}",\n	"nonce": "{{nonce}}",\n	"locale": "en_US",\n	"customer_ip": "127.0.0.1",\n	"session_id": "{{session_id}}",\n	"user_agent": "curl/7.64.0",\n	"system": "aft",\n	"configuration_id": {{configuration_id}},\n	"fare_group_key": "{{fare_group_key}}"\n}';

    const response = await makeApiCall(
      () => controller.fareRules(authorization, body)
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Seat_map', async () => {
    const authorization = 'Signature {{signature}}';

    const body = '{\n	"api_key": "{{ASB_API_KEY}}",\n	"timestamp": "{{timestamp}}",\n	"nonce": "{{nonce}}",\n	"locale": "en_US",\n	"customer_ip": "127.0.0.1",\n	"session_id": "{{session_id}}",\n	"user_agent": "curl/7.64.0",\n	"system": "aft",\n	\n	"configuration_id": {{configuration_id}},	\n	"fare_group_key": "{{fare_group_key}}",\n    "flight_option_keys": [\n        "{{flight_option_key_1}}"\n    ],\n	"traveler": {\n		"traveler_name": {\n			"first_name": "{{traveler_first_name}}",\n		    "last_name": "{{traveler_last_name}}"\n		}\n	}\n}';

    const response = await makeApiCall(
      () => controller.seatMap(authorization, body)
    );

    expect(response.statusCode).toBe(200);
  });
});
