/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  Hotelsbookrequest,
  HotelscancelReservationRequest,
  HotelsController,
  Hotelsrebookrequest,
  HotelsupdateReservationDetailsRequest,
} from '../src';
import { testClient } from './testClient.js';
import { makeApiCall } from './testHelper.js';

describe('HotelsController', () => {
  let controller : HotelsController;

  beforeAll(() => {
    controller = new HotelsController(testClient);
  });

  it('should Test Get_list', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const configurationId = 4;

    const system = 'aft';

    const destination = 'Region:e|2786';

    const chains = 'HH';

    const checkin = '2023-07-11';

    const hotelNameKeyword = 'Inn';

    const limit = 10;

    const order = 'name';

    const page = 1;

    const searchRadius = 5;

    const searchRadiusUnit = 'KM';

    const starRatingFilter = '4,4.5,5';

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getList(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        configurationId,
        system,
        destination,
        chains,
        checkin,
        hotelNameKeyword,
        limit,
        order,
        page,
        searchRadius,
        searchRadiusUnit,
        starRatingFilter,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Get_detailed_info', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const configurationId = 4;

    const system = 'aft';

    const checkin = '2021-07-11';

    const hotelId = 574889;

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getDetailedInfo(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        configurationId,
        system,
        checkin,
        hotelId,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Get_availability', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const configurationId = 4;

    const system = 'aft';

    const checkin = '2023-07-11';

    const checkout = '2023-07-12';

    const currency = 'EUR';

    const guestCount = 1;

    const hotels = 574889;

    const loyaltyProgramCodes = 'Z99';

    const onlyAvailableHotels = true;

    const returnPostpaidOnly = false;

    const timeout = 30;

    const dontWaitForResults = false;

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getAvailability(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        configurationId,
        system,
        checkin,
        checkout,
        currency,
        guestCount,
        hotels,
        loyaltyProgramCodes,
        onlyAvailableHotels,
        returnPostpaidOnly,
        timeout,
        dontWaitForResults,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Get_rates', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const configurationId = 4;

    const system = 'aft';

    const checkin = '2021-07-11';

    const checkout = '2021-07-12';

    const currency = 'EUR';

    const guestCount = 1;

    const hotelId = 574889;

    const loyaltyProgramCodes = 'Z99';

    const timeout = 60;

    const dateFormatType = 'fr';

    const dontWaitForResults = false;

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getRates(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        configurationId,
        system,
        checkin,
        checkout,
        currency,
        guestCount,
        hotelId,
        loyaltyProgramCodes,
        timeout,
        dateFormatType,
        dontWaitForResults,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Get_rate_details', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const configurationId = 4;

    const system = 'aft';

    const rateKey = 'eJxNTEtuwjAU3HOKd4AE7Edw3Nk58QNbhMRKUoTYIcGCql213L8JYsEsRqP5sWLOlc3XatQbaAM2S2W5KC1QAJuysPYDCAFP7IDLz+V6e/zOXgqNmVboXQ04xc3RAJXeA6xY56rMtX7TPIXWZ1Xw2VZ8Nq2ys3kefw7+RczFUuGFr8f3/fYHbBs5xaoR6t0oC0372O6oEr+ou0OiEGlIIp5iO0rfykgrcilN9Zjc7FLfdYd/eLc5NQ==';

    const guestCount = 1;

    const hotelId = 574889;

    const dateFormatType = 'fr';

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getRateDetails(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        configurationId,
        system,
        rateKey,
        guestCount,
        hotelId,
        dateFormatType,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Get_recommended_rate', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const configurationId = 4;

    const system = 'aft';

    const rateKey = 'eJxNTEtuwjAU3HOKd4AE7Edw3Nk58QNbhMRKUoTYIcGCql213L8JYsEsRqP5sWLOlc3XatQbaAM2S2W5KC1QAJuysPYDCAFP7IDLz+V6e/zOXgqNmVboXQ04xc3RAJXeA6xY56rMtX7TPIXWZ1Xw2VZ8Nq2ys3kefw7+RczFUuGFr8f3/fYHbBs5xaoR6t0oC0372O6oEr+ou0OiEGlIIp5iO0rfykgrcilN9Zjc7FLfdYd/eLc5NQ==';

    const guestCount = 1;

    const hotelId = 574889;

    const dateFormatType = 'fr';

    const searchId = '68lkU9QBGOmOLdrI2hlaSl';

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getRecommendedRate(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        configurationId,
        system,
        rateKey,
        guestCount,
        hotelId,
        dateFormatType,
        searchId,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Get_checkout_data', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const configurationId = 4;

    const system = 'aft';

    const acceptedCreditCards = 'VI,MC';

    const checkout = '2021-07-12';

    const internalTravelerId = 123;

    const paidPolicy = 'D';

    const tspmCompanyId = 20.001;

    const tspmTravelerId = 24.001;

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getCheckoutData(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        configurationId,
        system,
        acceptedCreditCards,
        checkout,
        internalTravelerId,
        paidPolicy,
        tspmCompanyId,
        tspmTravelerId,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Book', async () => {
    const authorization = 'Signature {{signature}}';

    const body: Hotelsbookrequest = {
      apiKey: '{{ASB_API_KEY}}',
      timestamp: '{{timestamp}}',
      nonce: '{{nonce}}',
      locale: 'en_US',
      customerIp: '127.0.0.1',
      sessionId: '{{session_id}}',
      userAgent: 'curl/7.64.0',
      configurationId: 4,
      system: 'aft',
      booktrackId: '{{timestamp}}',
      guestCount: 1,
      hotelId: 574889,
      originalCurrency: 'USD',
      originalTotal: 229.15,
      rateKey: 'eJxNjM0SwUAQhO+eYh5A2Bn5WX0bdsumkGwloYqbKg4UJ7y/hIs+dX/d1WJEEmOTGXeGIRmyfJKKFbZACmRFau0cCAFfrYDT43S+vJ8Di2GTcwbEpgbUiJo+LHgNiBFOTJEw/3npy+DG/Xp8zL+HftcAu9YBPC8mw+Cn2/t+vbz6T1VqOz2QVo5a3fsR07qsVrTwbrSst5FCSW303lFZdb6pfEdT0hg3nsqoA6WmrrcfzNk4Wg==',
      bookerEmail: 'booker@bcdtriptech.com',
      bookerFirstName: 'BookerFirst',
      bookerLastName: 'BookerLast',
      travelerEmail: 'traveler@bcdtriptech.com',
      travelerFirstName: 'TravelerFirst',
      travelerLastName: 'TravelerLast',
      paymentMethod: 'card',
      loyaltyCardChainCode: 'RT',
      loyaltyCardNumber: '1001709',
      creditCardNumber: '5555555555554444',
      creditCardExpirationYear: '2030',
      creditCardExpirationMonth: '01',
      creditCardFirstName: 'GHOST',
      creditCardLastName: 'CARD',
      creditCardAddress: 'addr1',
      creditCardCountryCode: 'US',
      creditCardCity: 'Atlanta',
      creditCardStateProvinceCode: 'GA',
      creditCardPostalCode: '12345',
      creditCardPhone: '1234567890',
    };

    const response = await makeApiCall(
      () => controller.book(authorization, body)
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Rebook', async () => {
    const authorization = 'Signature {{signature}}';

    const body: Hotelsrebookrequest = {
      apiKey: '{{ASB_API_KEY}}',
      timestamp: '{{timestamp}}',
      nonce: '{{nonce}}',
      locale: 'en_US',
      customerIp: '127.0.0.1',
      sessionId: '{{session_id}}',
      userAgent: 'curl/7.64.0',
      bookingUid: 'dc2ee73lfjykj4zliaqlm5xix',
      booktrackId: '{{timestamp}}',
      hotelId: 574889,
      originalCurrency: 'USD',
      originalTotal: 229.15,
      rateKey: 'eJxNjMtOwzAURPf9ivsBTWubvDq768SKrSaxFTtFsKtEFyBYQf8fp2yY1TyORgmlCtEWTzIJCVWhqg+lapVsgRKomrJtT4C1eGgArl/Xt9v9e+uCHWtZAWHxAIuSRQ6DPANKKFmIppDyn1eAtv0+0/vX+nFo1gVYYw/IU3PYgD993D/fbz/5k5li4hfiuafIF7OTdHbzQJPXbnQpD11nYnR6NPR8JM3JplXvOj8Fso5iMKYnNyezzCbRkTiETLrAW0uL99MvQXY/vQ==',
      bookerEmail: 'booker@bcdtriptech.com',
      bookerFirstName: 'BookerFirst',
      bookerLastName: 'BookerLast',
    };

    const response = await makeApiCall(
      () => controller.rebook(authorization, body)
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Cancel_reservation', async () => {
    const authorization = 'Signature {{signature}}';

    const body: HotelscancelReservationRequest = {
      apiKey: '{{ASB_API_KEY}}',
      timestamp: '{{timestamp}}',
      nonce: '{{nonce}}',
      locale: 'en_US',
      customerIp: '127.0.0.1',
      sessionId: '{{session_id}}',
      userAgent: 'curl/7.64.0',
      system: 'aft',
      email: 'booker@bcdtriptech.com',
      bookingUid: 'c45ku73jdbjlczjktkdzanpcmi',
    };

    const response = await makeApiCall(
      () => controller.cancelReservation(authorization, body)
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Update_reservation_details', async () => {
    const authorization = 'Signature {{signature}}';

    const body: HotelsupdateReservationDetailsRequest = {
      apiKey: '{{ASB_API_KEY}}',
      timestamp: '{{timestamp}}',
      nonce: '{{nonce}}',
      locale: 'en_US',
      customerIp: '127.0.0.1',
      sessionId: '{{session_id}}',
      userAgent: 'curl/7.64.0',
      system: 'aft',
      bookingUid: 'dc2ee73lfjykj4zliaqlm5xix',
      bookingData: {
        isGhost: false,
      },
    };

    const response = await makeApiCall(
      () => controller.updateReservationDetails(authorization, body)
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Get_reservations_list', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const configurationId = 4;

    const system = 'aft';

    const travelerEmail = 'traveler@bcdtriptech.com';

    const status = 'canceled';

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getReservationsList(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        configurationId,
        system,
        travelerEmail,
        status,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test Get_reservation_details', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const system = 'aft';

    const travelerEmail = 'traveler@bcdtriptech.com';

    const bookingUid = 'c45ku73jdbjlczjktkdzanpcmi';

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getReservationDetails(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        system,
        travelerEmail,
        bookingUid,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });
});
