/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { V20Controller } from '../src';
import { testClient } from './testClient.js';
import { makeApiCall } from './testHelper.js';

describe('V20Controller', () => {
  let controller : V20Controller;

  beforeAll(() => {
    controller = new V20Controller(testClient);
  });

  it('should Test get_profile_info', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const configurationId = 4;

    const system = 'aft';

    const travelerEmail = 'traveler@email.com';

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getProfileInfo(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        configurationId,
        system,
        travelerEmail,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });
});
