/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  GetConfigurationsPOSTRequest,
  PingGETRESPONSE,
  Pingrequest,
  V21Controller,
} from '../src';
import { testClient } from './testClient.js';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper.js';

describe('V21Controller', () => {
  let controller : V21Controller;

  beforeAll(() => {
    controller = new V21Controller(testClient);
  });

  it('should Test ping', async () => {
    const authorization = 'Signature {{signature}}';

    const body: Pingrequest = {
      apiKey: '{{ASB_API_KEY}}',
      timestamp: '{{timestamp}}',
      nonce: '{{nonce}}',
      locale: 'en_US',
      customerIp: '127.0.0.1',
      sessionId: '{{session_id}}',
      userAgent: 'curl/7.64.0',
    };

    const response = await makeApiCall(
      () => controller.ping(authorization, body)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      Server: ['', false],
      Date: ['', false],
      Connection: ['', false],
      Vary: ['', false],
      Allow: ['', false],
      'Content-Length': ['', false],
      'Set-Cookie': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: PingGETRESPONSE = {
      ping: 'pong, v2.0',
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test getPing', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getPing(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      Server: ['', false],
      Date: ['', false],
      Connection: ['', false],
      Vary: ['', false],
      Allow: ['', false],
      'Content-Length': ['', false],
      'Set-Cookie': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: PingGETRESPONSE = {
      ping: 'pong, v2.0',
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test destination_lookup', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const system = 'aft';

    const configurationId = 4;

    const categoryList = 'cities';

    const categoryMaxResults = 3;

    const term = 'Philadelphia';

    const product = 'hotels';

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.destinationLookup(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        system,
        configurationId,
        categoryList,
        categoryMaxResults,
        term,
        product,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test get_company_locations', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const system = 'aft';

    const configurationId = 4;

    const destination = 'Region:e|2786';

    const searchRadius = 10;

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getCompanyLocations(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        system,
        configurationId,
        destination,
        searchRadius,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test get_company_settings', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const system = 'aft';

    const configurationId = 4;

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getCompanySettings(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        system,
        configurationId,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test get_configurations', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const system = 'aft';

    const fallbackEntityId = 4;

    const travelerEmail = 'traveler@email.com';

    const pnrId = 'NQ86M3';

    const tspmCompanyId = 20.14881;

    const smidCompanyId = 'SMID.14881';

    const obtCompanyId = 4;

    const entityId = 6;

    const tspmTravelerId = 24.100000037;

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getConfigurations(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        system,
        fallbackEntityId,
        travelerEmail,
        pnrId,
        tspmCompanyId,
        smidCompanyId,
        obtCompanyId,
        entityId,
        tspmTravelerId,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test get_configurationsPOST', async () => {
    const authorization = 'Signature {{signature}}';

    const body: GetConfigurationsPOSTRequest = {
      apiKey: '{{ASB_API_KEY}}',
      timestamp: '{{timestamp}}',
      nonce: '{{nonce}}',
      locale: 'en_US',
      customerIp: '127.0.0.1',
      sessionId: '{{session_id}}',
      userAgent: 'curl/7.64.0',
      entityId: 4,
      system: 'aft',
      tspmCompanyId: '20.14881',
      tspmTravelerId: '24.100000037',
      clientReportableData: [
        {
          code: 'AFT.COMMON.CRD.vip_person',
          answer: 'ans1',
        }
      ],
      pnrId: 'NQ86M3',
    };

    const response = await makeApiCall(
      () => controller.getConfigurationsPOST(authorization, body)
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test get_entity_id', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const system = 'aft';

    const fallbackEntityId = 4;

    const travelerEmail = 'traveler@email.com';

    const pnrId = 'NQ86M3';

    const tspmCompanyId = 20.14881;

    const smidCompanyId = 'SMID.14881';

    const obtCompanyId = 4;

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getEntityId(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        system,
        fallbackEntityId,
        travelerEmail,
        pnrId,
        tspmCompanyId,
        smidCompanyId,
        obtCompanyId,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Test get_errors', async () => {
    const apiKey = '{{ASB_API_KEY}}';

    const timestamp = '{{timestamp}}';

    const nonce = '{{nonce}}';

    const locale = 'en_US';

    const customerIp = '127.0.0.1';

    const sessionId = '{{session_id}}';

    const userAgent = 'curl/7.64.0';

    const authorization = 'Signature {{signature}}';

    const response = await makeApiCall(
      () => controller.getErrors(
        apiKey,
        timestamp,
        nonce,
        locale,
        customerIp,
        sessionId,
        userAgent,
        authorization
      )
    );

    expect(response.statusCode).toBe(200);
  });
});
