/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, oneOf, Schema } from '../../schema.js';

/** This is a container type for one-of types. */
export type BaseFare1Amount = number;

export const baseFare1AmountSchema: Schema<BaseFare1Amount> = oneOf([number()]);

export namespace BaseFare1Amount {
  /**
   * Validation method to narrow down union type to number type case.
   *
   * This is Precision case.
   */
  export function isNumber(value: unknown): value is number {
    return typeof value === 'number';
  }
}
