/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import { LineItem, lineItemSchema } from '../lineItem.js';
import { LineItem1, lineItem1Schema } from '../lineItem1.js';

/** This is a container type for one-of types. */
export type DocumentLineItems = LineItem | LineItem1;

export const documentLineItemsSchema: Schema<DocumentLineItems> = lazy(() =>
  oneOf([lineItemSchema, lineItem1Schema])
);

export namespace DocumentLineItems {
  /**
   * Validation method to narrow down union type to LineItem type case.
   *
   * This is LineItem case.
   */
  export function isLineItem(value: unknown): value is LineItem {
    return isMappedValueValidForSchema(value, lineItemSchema);
  }

  /**
   * Validation method to narrow down union type to LineItem1 type case.
   *
   * This is LineItem1 case.
   */
  export function isLineItem1(value: unknown): value is LineItem1 {
    return isMappedValueValidForSchema(value, lineItem1Schema);
  }
}
