/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, oneOf, Schema } from '../../schema.js';

/** This is a container type for one-of types. */
export type Fare2Amount = number;

export const fare2AmountSchema: Schema<Fare2Amount> = oneOf([number()]);

export namespace Fare2Amount {
  /**
   * Validation method to narrow down union type to number type case.
   *
   * This is Number case.
   */
  export function isNumber(value: unknown): value is number {
    return typeof value === 'number';
  }
}
