/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, oneOf, Schema } from '../../schema.js';

/** This is a container type for one-of types. */
export type TaxisAmount = number;

export const taxisAmountSchema: Schema<TaxisAmount> = oneOf([number()]);

export namespace TaxisAmount {
  /**
   * Validation method to narrow down union type to number type case.
   *
   * This is Number case.
   */
  export function isNumber(value: unknown): value is number {
    return typeof value === 'number';
  }
}
