/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
  string,
} from '../../schema.js';
import { Leg33, leg33Schema } from '../leg33.js';

/** This is a container type for one-of types. */
export type Ticket32Legs = Leg33 | string;

export const ticket32LegsSchema: Schema<Ticket32Legs> = lazy(() =>
  oneOf([leg33Schema, string()])
);

export namespace Ticket32Legs {
  /**
   * Validation method to narrow down union type to Leg33 type case.
   *
   * This is Leg33 case.
   */
  export function isLeg33(value: unknown): value is Leg33 {
    return isMappedValueValidForSchema(value, leg33Schema);
  }

  /**
   * Validation method to narrow down union type to string type case.
   *
   * This is String case.
   */
  export function isString(value: unknown): value is string {
    return typeof value === 'string';
  }
}
