/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
  string,
} from '../../schema.js';
import { Leg, legSchema } from '../leg.js';

/** This is a container type for one-of types. */
export type Ticket4Legs = Leg | string;

export const ticket4LegsSchema: Schema<Ticket4Legs> = lazy(() =>
  oneOf([legSchema, string()])
);

export namespace Ticket4Legs {
  /**
   * Validation method to narrow down union type to Leg type case.
   *
   * This is Leg case.
   */
  export function isLeg(value: unknown): value is Leg {
    return isMappedValueValidForSchema(value, legSchema);
  }

  /**
   * Validation method to narrow down union type to string type case.
   *
   * This is String case.
   */
  export function isString(value: unknown): value is string {
    return typeof value === 'string';
  }
}
