/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AircompleteVerificationRequest,
  aircompleteVerificationRequestSchema,
} from '../models/aircompleteVerificationRequest.js';
import {
  AirdocumentsIssueRequest,
  airdocumentsIssueRequestSchema,
} from '../models/airdocumentsIssueRequest.js';
import {
  AirretrieveReservationsListRequest,
  airretrieveReservationsListRequestSchema,
} from '../models/airretrieveReservationsListRequest.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class AirApi extends BaseApi {
  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param system
   * @param term
   * @param authorization
   * @return Response from the API call
   */
  async mAirDestinationLookupApiKeyAsbApiKeyTimestampTimestampNonceNonceLocaleEnUsCustomerIp127001SessionIdSessionIdUserAgentCurl7640SystemAftConfigurationId4TermIrpin(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    system: string,
    term: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/air/destination_lookup');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      system: [system, string()],
      term: [term, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('system', mapped.system);
    req.query('term', mapped.term);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async mAirDocumentsIssue(
    authorization: string,
    body: AirdocumentsIssueRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/air/documents_issue');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, airdocumentsIssueRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async mAirCompleteVerification(
    authorization: string,
    body: AircompleteVerificationRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/air/complete_verification');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, aircompleteVerificationRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async mAirRetrieveReservationsList(
    authorization: string,
    body: AirretrieveReservationsListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/air/retrieve_reservations_list');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, airretrieveReservationsListRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }
}
