/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { ContentType, contentTypeSchema } from '../models/contentType.js';
import {
  HotelscancelReservationRequest,
  hotelscancelReservationRequestSchema,
} from '../models/hotelscancelReservationRequest.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class AirFareSearchSimpleApi extends BaseApi {
  /**
   * @param authorization
   * @param contentType
   * @return Response from the API call
   */
  async init(
    authorization: string,
    contentType: ContentType,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/1');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      contentType: [contentType, contentTypeSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', mapped.contentType);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async mAirFareSearch(
    authorization: string,
    body: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/air/fare_search');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.text(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async mAirPricing(
    authorization: string,
    body: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/air/pricing');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.text(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async mAirBook(
    authorization: string,
    body: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/air/book');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.text(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async wait10Seconds(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/10');
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param system
   * @param bookingUid
   * @param currency
   * @param authorization
   * @return Response from the API call
   */
  async mAirGetReservationDetails(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    system: string,
    bookingUid: string,
    currency: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/air/get_reservation_details');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      system: [system, string()],
      bookingUid: [bookingUid, string()],
      currency: [currency, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('system', mapped.system);
    req.query('booking_uid', mapped.bookingUid);
    req.query('currency', mapped.currency);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async mAirCancelReservation(
    authorization: string,
    body: HotelscancelReservationRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/air/cancel_reservation');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, hotelscancelReservationRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }
}
