/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class AirFareSearchOptionalServicesApi extends BaseApi {
  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async mAirGetCheckoutData(
    authorization: string,
    body: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/air/get_checkout_data');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'text/plain');
    req.text(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }
}
