/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { string } from '../schema.js';
import { BaseController } from './baseController.js';

export class AirFareSearchSelectSeatController extends BaseController {
  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async fareRules(
    authorization: string,
    body: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/air/fare_rules');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.text(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async seatMap(
    authorization: string,
    body: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/air/seat_map');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.text(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }
}
