/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  Carsbookcardrequest,
  carsbookcardrequestSchema,
} from '../models/carsbookcardrequest.js';
import {
  CarsdirectSellBooknoPaymentrequest,
  carsdirectSellBooknoPaymentrequestSchema,
} from '../models/carsdirectSellBooknoPaymentrequest.js';
import {
  CarsmodifyReservationRequest,
  carsmodifyReservationRequestSchema,
} from '../models/carsmodifyReservationRequest.js';
import {
  CarsretrieveReservationsListRequest,
  carsretrieveReservationsListRequestSchema,
} from '../models/carsretrieveReservationsListRequest.js';
import {
  HotelscancelReservationRequest,
  hotelscancelReservationRequestSchema,
} from '../models/hotelscancelReservationRequest.js';
import { number, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class CarsApi extends BaseApi {
  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param system
   * @param configurationId
   * @param currency
   * @param pickupLocation
   * @param pickupDatetime
   * @param dropoffDatetime
   * @param searchRadiusUnit
   * @param idNumbers
   * @param cdNumbers
   * @param carTypes
   * @param vendorCodes
   * @param authorization
   * @return Response from the API call
   */
  async mCarsGetAvailability(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    system: string,
    configurationId: number,
    currency: string,
    pickupLocation: string,
    pickupDatetime: string,
    dropoffDatetime: string,
    searchRadiusUnit: string,
    idNumbers: string,
    cdNumbers: string,
    carTypes: string,
    vendorCodes: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/cars/get_availability');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      system: [system, string()],
      configurationId: [configurationId, number()],
      currency: [currency, string()],
      pickupLocation: [pickupLocation, string()],
      pickupDatetime: [pickupDatetime, string()],
      dropoffDatetime: [dropoffDatetime, string()],
      searchRadiusUnit: [searchRadiusUnit, string()],
      idNumbers: [idNumbers, string()],
      cdNumbers: [cdNumbers, string()],
      carTypes: [carTypes, string()],
      vendorCodes: [vendorCodes, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('system', mapped.system);
    req.query('configuration_id', mapped.configurationId);
    req.query('currency', mapped.currency);
    req.query('pickup_location', mapped.pickupLocation);
    req.query('pickup_datetime', mapped.pickupDatetime);
    req.query('dropoff_datetime', mapped.dropoffDatetime);
    req.query('search_radius_unit', mapped.searchRadiusUnit);
    req.query('id_numbers', mapped.idNumbers);
    req.query('cd_numbers', mapped.cdNumbers);
    req.query('car_types', mapped.carTypes);
    req.query('vendor_codes', mapped.vendorCodes);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param system
   * @param configurationId
   * @param rateKey
   * @param authorization
   * @return Response from the API call
   */
  async mCarsGetRateDetails(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    system: string,
    configurationId: number,
    rateKey: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/cars/get_rate_details');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      system: [system, string()],
      configurationId: [configurationId, number()],
      rateKey: [rateKey, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('system', mapped.system);
    req.query('configuration_id', mapped.configurationId);
    req.query('rate_key', mapped.rateKey);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param system
   * @param configurationId
   * @param rateKey
   * @param internalTravelerId
   * @param tspmTravelerId
   * @param tspmCompanyId
   * @param authorization
   * @return Response from the API call
   */
  async mCarsGetCheckoutData(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    system: string,
    configurationId: number,
    rateKey: string,
    internalTravelerId: number,
    tspmTravelerId: number,
    tspmCompanyId: number,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/cars/get_checkout_data');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      system: [system, string()],
      configurationId: [configurationId, number()],
      rateKey: [rateKey, string()],
      internalTravelerId: [internalTravelerId, number()],
      tspmTravelerId: [tspmTravelerId, number()],
      tspmCompanyId: [tspmCompanyId, number()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('system', mapped.system);
    req.query('configuration_id', mapped.configurationId);
    req.query('rate_key', mapped.rateKey);
    req.query('internal_traveler_id', mapped.internalTravelerId);
    req.query('tspm_traveler_id', mapped.tspmTravelerId);
    req.query('tspm_company_id', mapped.tspmCompanyId);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param system
   * @param configurationId
   * @param tspmTravelerId
   * @param tspmCompanyId
   * @param vendorCode
   * @param authorization
   * @return Response from the API call
   */
  async mCarsGetDirectSellCheckoutData(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    system: string,
    configurationId: number,
    tspmTravelerId: number,
    tspmCompanyId: number,
    vendorCode: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest(
      'GET',
      '/cars/get_direct_sell_checkout_data'
    );
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      system: [system, string()],
      configurationId: [configurationId, number()],
      tspmTravelerId: [tspmTravelerId, number()],
      tspmCompanyId: [tspmCompanyId, number()],
      vendorCode: [vendorCode, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('system', mapped.system);
    req.query('configuration_id', mapped.configurationId);
    req.query('tspm_traveler_id', mapped.tspmTravelerId);
    req.query('tspm_company_id', mapped.tspmCompanyId);
    req.query('vendor_code', mapped.vendorCode);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async mCarsBookCard(
    authorization: string,
    body: Carsbookcardrequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/cars/book');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, carsbookcardrequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async mCarsModifyReservation(
    authorization: string,
    body: CarsmodifyReservationRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/cars/modify_reservation');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, carsmodifyReservationRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async mCarsDirectSellBookNoPayment(
    authorization: string,
    body: CarsdirectSellBooknoPaymentrequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/cars/direct_sell_book');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, carsdirectSellBooknoPaymentrequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async mCarsCancelReservation(
    authorization: string,
    body: HotelscancelReservationRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/cars/cancel_reservation');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, hotelscancelReservationRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param system
   * @param travelerEmail
   * @param status
   * @param authorization
   * @return Response from the API call
   */
  async mCarsGetReservationsList(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    system: string,
    travelerEmail: string,
    status: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/cars/get_reservations_list');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      system: [system, string()],
      travelerEmail: [travelerEmail, string()],
      status: [status, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('system', mapped.system);
    req.query('traveler_email', mapped.travelerEmail);
    req.query('status', mapped.status);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async mCarsRetrieveReservationsList(
    authorization: string,
    body: CarsretrieveReservationsListRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/cars/retrieve_reservations_list');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, carsretrieveReservationsListRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param system
   * @param bookingUid
   * @param authorization
   * @return Response from the API call
   */
  async mCarsGetReservationDetails(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    system: string,
    bookingUid: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/cars/get_reservation_details');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      system: [system, string()],
      bookingUid: [bookingUid, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('system', mapped.system);
    req.query('booking_uid', mapped.bookingUid);
    req.authenticate(false);
    return req.call(requestOptions);
  }
}
