/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  Hotelsbookrequest,
  hotelsbookrequestSchema,
} from '../models/hotelsbookrequest.js';
import {
  HotelscancelReservationRequest,
  hotelscancelReservationRequestSchema,
} from '../models/hotelscancelReservationRequest.js';
import {
  Hotelsrebookrequest,
  hotelsrebookrequestSchema,
} from '../models/hotelsrebookrequest.js';
import {
  HotelsupdateReservationDetailsRequest,
  hotelsupdateReservationDetailsRequestSchema,
} from '../models/hotelsupdateReservationDetailsRequest.js';
import { boolean, number, string } from '../schema.js';
import { BaseController } from './baseController.js';

export class HotelsController extends BaseController {
  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param configurationId
   * @param system
   * @param destination
   * @param chains
   * @param checkin
   * @param hotelNameKeyword
   * @param limit
   * @param order
   * @param page
   * @param searchRadius
   * @param searchRadiusUnit
   * @param starRatingFilter
   * @param authorization
   * @return Response from the API call
   */
  async getList(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    configurationId: number,
    system: string,
    destination: string,
    chains: string,
    checkin: string,
    hotelNameKeyword: string,
    limit: number,
    order: string,
    page: number,
    searchRadius: number,
    searchRadiusUnit: string,
    starRatingFilter: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/hotels/get_list');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      configurationId: [configurationId, number()],
      system: [system, string()],
      destination: [destination, string()],
      chains: [chains, string()],
      checkin: [checkin, string()],
      hotelNameKeyword: [hotelNameKeyword, string()],
      limit: [limit, number()],
      order: [order, string()],
      page: [page, number()],
      searchRadius: [searchRadius, number()],
      searchRadiusUnit: [searchRadiusUnit, string()],
      starRatingFilter: [starRatingFilter, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('configuration_id', mapped.configurationId);
    req.query('system', mapped.system);
    req.query('destination', mapped.destination);
    req.query('chains', mapped.chains);
    req.query('checkin', mapped.checkin);
    req.query('hotel_name_keyword', mapped.hotelNameKeyword);
    req.query('limit', mapped.limit);
    req.query('order', mapped.order);
    req.query('page', mapped.page);
    req.query('search_radius', mapped.searchRadius);
    req.query('search_radius_unit', mapped.searchRadiusUnit);
    req.query('star_rating_filter', mapped.starRatingFilter);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param configurationId
   * @param system
   * @param checkin
   * @param hotelId
   * @param authorization
   * @return Response from the API call
   */
  async getDetailedInfo(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    configurationId: number,
    system: string,
    checkin: string,
    hotelId: number,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/hotels/get_detailed_info');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      configurationId: [configurationId, number()],
      system: [system, string()],
      checkin: [checkin, string()],
      hotelId: [hotelId, number()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('configuration_id', mapped.configurationId);
    req.query('system', mapped.system);
    req.query('checkin', mapped.checkin);
    req.query('hotel_id', mapped.hotelId);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param configurationId
   * @param system
   * @param checkin
   * @param checkout
   * @param currency
   * @param guestCount
   * @param hotels
   * @param loyaltyProgramCodes
   * @param onlyAvailableHotels
   * @param returnPostpaidOnly
   * @param timeout
   * @param dontWaitForResults
   * @param authorization
   * @return Response from the API call
   */
  async getAvailability(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    configurationId: number,
    system: string,
    checkin: string,
    checkout: string,
    currency: string,
    guestCount: number,
    hotels: number,
    loyaltyProgramCodes: string,
    onlyAvailableHotels: boolean,
    returnPostpaidOnly: boolean,
    timeout: number,
    dontWaitForResults: boolean,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/hotels/get_availability');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      configurationId: [configurationId, number()],
      system: [system, string()],
      checkin: [checkin, string()],
      checkout: [checkout, string()],
      currency: [currency, string()],
      guestCount: [guestCount, number()],
      hotels: [hotels, number()],
      loyaltyProgramCodes: [loyaltyProgramCodes, string()],
      onlyAvailableHotels: [onlyAvailableHotels, boolean()],
      returnPostpaidOnly: [returnPostpaidOnly, boolean()],
      timeout: [timeout, number()],
      dontWaitForResults: [dontWaitForResults, boolean()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('configuration_id', mapped.configurationId);
    req.query('system', mapped.system);
    req.query('checkin', mapped.checkin);
    req.query('checkout', mapped.checkout);
    req.query('currency', mapped.currency);
    req.query('guest_count', mapped.guestCount);
    req.query('hotels', mapped.hotels);
    req.query('loyalty_program_codes', mapped.loyaltyProgramCodes);
    req.query('only_available_hotels', mapped.onlyAvailableHotels);
    req.query('return_postpaid_only', mapped.returnPostpaidOnly);
    req.query('timeout', mapped.timeout);
    req.query('dont_wait_for_results', mapped.dontWaitForResults);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param configurationId
   * @param system
   * @param checkin
   * @param checkout
   * @param currency
   * @param guestCount
   * @param hotelId
   * @param loyaltyProgramCodes
   * @param timeout
   * @param dateFormatType
   * @param dontWaitForResults
   * @param authorization
   * @return Response from the API call
   */
  async getRates(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    configurationId: number,
    system: string,
    checkin: string,
    checkout: string,
    currency: string,
    guestCount: number,
    hotelId: number,
    loyaltyProgramCodes: string,
    timeout: number,
    dateFormatType: string,
    dontWaitForResults: boolean,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/hotels/get_rates');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      configurationId: [configurationId, number()],
      system: [system, string()],
      checkin: [checkin, string()],
      checkout: [checkout, string()],
      currency: [currency, string()],
      guestCount: [guestCount, number()],
      hotelId: [hotelId, number()],
      loyaltyProgramCodes: [loyaltyProgramCodes, string()],
      timeout: [timeout, number()],
      dateFormatType: [dateFormatType, string()],
      dontWaitForResults: [dontWaitForResults, boolean()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('configuration_id', mapped.configurationId);
    req.query('system', mapped.system);
    req.query('checkin', mapped.checkin);
    req.query('checkout', mapped.checkout);
    req.query('currency', mapped.currency);
    req.query('guest_count', mapped.guestCount);
    req.query('hotel_id', mapped.hotelId);
    req.query('loyalty_program_codes', mapped.loyaltyProgramCodes);
    req.query('timeout', mapped.timeout);
    req.query('date_format_type', mapped.dateFormatType);
    req.query('dont_wait_for_results', mapped.dontWaitForResults);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param configurationId
   * @param system
   * @param rateKey
   * @param guestCount
   * @param hotelId
   * @param dateFormatType
   * @param authorization
   * @return Response from the API call
   */
  async getRateDetails(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    configurationId: number,
    system: string,
    rateKey: string,
    guestCount: number,
    hotelId: number,
    dateFormatType: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/hotels/get_rate_details');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      configurationId: [configurationId, number()],
      system: [system, string()],
      rateKey: [rateKey, string()],
      guestCount: [guestCount, number()],
      hotelId: [hotelId, number()],
      dateFormatType: [dateFormatType, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('configuration_id', mapped.configurationId);
    req.query('system', mapped.system);
    req.query('rate_key', mapped.rateKey);
    req.query('guest_count', mapped.guestCount);
    req.query('hotel_id', mapped.hotelId);
    req.query('date_format_type', mapped.dateFormatType);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param configurationId
   * @param system
   * @param rateKey
   * @param guestCount
   * @param hotelId
   * @param dateFormatType
   * @param searchId
   * @param authorization
   * @return Response from the API call
   */
  async getRecommendedRate(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    configurationId: number,
    system: string,
    rateKey: string,
    guestCount: number,
    hotelId: number,
    dateFormatType: string,
    searchId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/hotels/get_recommended_rate');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      configurationId: [configurationId, number()],
      system: [system, string()],
      rateKey: [rateKey, string()],
      guestCount: [guestCount, number()],
      hotelId: [hotelId, number()],
      dateFormatType: [dateFormatType, string()],
      searchId: [searchId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('configuration_id', mapped.configurationId);
    req.query('system', mapped.system);
    req.query('rate_key', mapped.rateKey);
    req.query('guest_count', mapped.guestCount);
    req.query('hotel_id', mapped.hotelId);
    req.query('date_format_type', mapped.dateFormatType);
    req.query('search_id', mapped.searchId);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param configurationId
   * @param system
   * @param acceptedCreditCards
   * @param checkout
   * @param internalTravelerId
   * @param paidPolicy
   * @param tspmCompanyId
   * @param tspmTravelerId
   * @param authorization
   * @return Response from the API call
   */
  async getCheckoutData(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    configurationId: number,
    system: string,
    acceptedCreditCards: string,
    checkout: string,
    internalTravelerId: number,
    paidPolicy: string,
    tspmCompanyId: number,
    tspmTravelerId: number,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/hotels/get_checkout_data');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      configurationId: [configurationId, number()],
      system: [system, string()],
      acceptedCreditCards: [acceptedCreditCards, string()],
      checkout: [checkout, string()],
      internalTravelerId: [internalTravelerId, number()],
      paidPolicy: [paidPolicy, string()],
      tspmCompanyId: [tspmCompanyId, number()],
      tspmTravelerId: [tspmTravelerId, number()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('configuration_id', mapped.configurationId);
    req.query('system', mapped.system);
    req.query('accepted_credit_cards', mapped.acceptedCreditCards);
    req.query('checkout', mapped.checkout);
    req.query('internal_traveler_id', mapped.internalTravelerId);
    req.query('paid_policy', mapped.paidPolicy);
    req.query('tspm_company_id', mapped.tspmCompanyId);
    req.query('tspm_traveler_id', mapped.tspmTravelerId);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async book(
    authorization: string,
    body: Hotelsbookrequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/hotels/book');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, hotelsbookrequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async rebook(
    authorization: string,
    body: Hotelsrebookrequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/hotels/rebook');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, hotelsrebookrequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async cancelReservation(
    authorization: string,
    body: HotelscancelReservationRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/hotels/cancel_reservation');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, hotelscancelReservationRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async updateReservationDetails(
    authorization: string,
    body: HotelsupdateReservationDetailsRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest(
      'POST',
      '/hotels/update_reservation_details'
    );
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, hotelsupdateReservationDetailsRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param configurationId
   * @param system
   * @param travelerEmail
   * @param status
   * @param authorization
   * @return Response from the API call
   */
  async getReservationsList(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    configurationId: number,
    system: string,
    travelerEmail: string,
    status: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/hotels/get_reservations_list');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      configurationId: [configurationId, number()],
      system: [system, string()],
      travelerEmail: [travelerEmail, string()],
      status: [status, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('configuration_id', mapped.configurationId);
    req.query('system', mapped.system);
    req.query('traveler_email', mapped.travelerEmail);
    req.query('status', mapped.status);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param system
   * @param travelerEmail
   * @param bookingUid
   * @param authorization
   * @return Response from the API call
   */
  async getReservationDetails(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    system: string,
    travelerEmail: string,
    bookingUid: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/hotels/get_reservation_details');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      system: [system, string()],
      travelerEmail: [travelerEmail, string()],
      bookingUid: [bookingUid, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('system', mapped.system);
    req.query('traveler_email', mapped.travelerEmail);
    req.query('booking_uid', mapped.bookingUid);
    req.authenticate(false);
    return req.call(requestOptions);
  }
}
