/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  GetVersionsbytripId,
  getVersionsbytripIdSchema,
} from '../models/getVersionsbytripId.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class RetrieveVersionsApi extends BaseApi {
  /**
   * The Retrieve Expense Versions Request will return versions of an expense item by its trip identifier.
   * Request is configured via URL link only. Filters are not supported by this API.
   *
   * > **tripId -** A unique identifier of an Expense in BCD (guid).
   *
   * @param tripId
   * @return Response from the API call
   */
  async getVersionsbytripId(
    tripId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetVersionsbytripId>> {
    const req = this.createRequest('GET');
    req.baseUrl('default1');
    const mapped = req.prepareArgs({ tripId: [tripId, string()] });
    req.appendTemplatePath`/v1/expenses/${mapped.tripId}/versions`;
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(getVersionsbytripIdSchema, requestOptions);
  }
}
