/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { number, string } from '../schema.js';
import { BaseController } from './baseController.js';

export class V20Controller extends BaseController {
  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param configurationId
   * @param system
   * @param travelerEmail
   * @param authorization
   * @return Response from the API call
   */
  async getProfileInfo(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    configurationId: number,
    system: string,
    travelerEmail: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/get_profile_info');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      configurationId: [configurationId, number()],
      system: [system, string()],
      travelerEmail: [travelerEmail, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('configuration_id', mapped.configurationId);
    req.query('system', mapped.system);
    req.query('traveler_email', mapped.travelerEmail);
    req.authenticate(false);
    return req.call(requestOptions);
  }
}
