/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  GetConfigurationsPOSTRequest,
  getConfigurationsPOSTRequestSchema,
} from '../models/getConfigurationsPOSTRequest.js';
import {
  PingGETRESPONSE,
  pingGETRESPONSESchema,
} from '../models/pingGETRESPONSE.js';
import { Pingrequest, pingrequestSchema } from '../models/pingrequest.js';
import { number, string } from '../schema.js';
import { BaseController } from './baseController.js';

export class V21Controller extends BaseController {
  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async ping(
    authorization: string,
    body: Pingrequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PingGETRESPONSE>> {
    const req = this.createRequest('POST', '/ping');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, pingrequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.callAsJson(pingGETRESPONSESchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param authorization
   * @return Response from the API call
   */
  async getPing(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PingGETRESPONSE>> {
    const req = this.createRequest('GET', '/ping');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.authenticate(false);
    return req.callAsJson(pingGETRESPONSESchema, requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param system
   * @param configurationId
   * @param categoryList
   * @param categoryMaxResults
   * @param term
   * @param product
   * @param authorization
   * @return Response from the API call
   */
  async destinationLookup(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    system: string,
    configurationId: number,
    categoryList: string,
    categoryMaxResults: number,
    term: string,
    product: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/destination_lookup');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      system: [system, string()],
      configurationId: [configurationId, number()],
      categoryList: [categoryList, string()],
      categoryMaxResults: [categoryMaxResults, number()],
      term: [term, string()],
      product: [product, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('system', mapped.system);
    req.query('configuration_id', mapped.configurationId);
    req.query('category_list', mapped.categoryList);
    req.query('category_max_results', mapped.categoryMaxResults);
    req.query('term', mapped.term);
    req.query('product', mapped.product);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param system
   * @param configurationId
   * @param destination
   * @param searchRadius
   * @param authorization
   * @return Response from the API call
   */
  async getCompanyLocations(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    system: string,
    configurationId: number,
    destination: string,
    searchRadius: number,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/get_company_locations');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      system: [system, string()],
      configurationId: [configurationId, number()],
      destination: [destination, string()],
      searchRadius: [searchRadius, number()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('system', mapped.system);
    req.query('configuration_id', mapped.configurationId);
    req.query('destination', mapped.destination);
    req.query('search_radius', mapped.searchRadius);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param system
   * @param configurationId
   * @param authorization
   * @return Response from the API call
   */
  async getCompanySettings(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    system: string,
    configurationId: number,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/get_company_settings');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      system: [system, string()],
      configurationId: [configurationId, number()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('system', mapped.system);
    req.query('configuration_id', mapped.configurationId);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param system
   * @param fallbackEntityId
   * @param travelerEmail
   * @param pnrId
   * @param tspmCompanyId
   * @param smidCompanyId
   * @param obtCompanyId
   * @param entityId
   * @param tspmTravelerId
   * @param authorization
   * @return Response from the API call
   */
  async getConfigurations(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    system: string,
    fallbackEntityId: number,
    travelerEmail: string,
    pnrId: string,
    tspmCompanyId: number,
    smidCompanyId: string,
    obtCompanyId: number,
    entityId: number,
    tspmTravelerId: number,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/get_configurations');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      system: [system, string()],
      fallbackEntityId: [fallbackEntityId, number()],
      travelerEmail: [travelerEmail, string()],
      pnrId: [pnrId, string()],
      tspmCompanyId: [tspmCompanyId, number()],
      smidCompanyId: [smidCompanyId, string()],
      obtCompanyId: [obtCompanyId, number()],
      entityId: [entityId, number()],
      tspmTravelerId: [tspmTravelerId, number()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('system', mapped.system);
    req.query('fallback_entity_id', mapped.fallbackEntityId);
    req.query('traveler_email', mapped.travelerEmail);
    req.query('pnr_id', mapped.pnrId);
    req.query('tspm_company_id', mapped.tspmCompanyId);
    req.query('smid_company_id', mapped.smidCompanyId);
    req.query('obt_company_id', mapped.obtCompanyId);
    req.query('entity_id', mapped.entityId);
    req.query('tspm_traveler_id', mapped.tspmTravelerId);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param authorization
   * @param body
   * @return Response from the API call
   */
  async getConfigurationsPOST(
    authorization: string,
    body: GetConfigurationsPOSTRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/get_configurations');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, getConfigurationsPOSTRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param system
   * @param fallbackEntityId
   * @param travelerEmail
   * @param pnrId
   * @param tspmCompanyId
   * @param smidCompanyId
   * @param obtCompanyId
   * @param authorization
   * @return Response from the API call
   */
  async getEntityId(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    system: string,
    fallbackEntityId: number,
    travelerEmail: string,
    pnrId: string,
    tspmCompanyId: number,
    smidCompanyId: string,
    obtCompanyId: number,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/get_entity_id');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      system: [system, string()],
      fallbackEntityId: [fallbackEntityId, number()],
      travelerEmail: [travelerEmail, string()],
      pnrId: [pnrId, string()],
      tspmCompanyId: [tspmCompanyId, number()],
      smidCompanyId: [smidCompanyId, string()],
      obtCompanyId: [obtCompanyId, number()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.query('system', mapped.system);
    req.query('fallback_entity_id', mapped.fallbackEntityId);
    req.query('traveler_email', mapped.travelerEmail);
    req.query('pnr_id', mapped.pnrId);
    req.query('tspm_company_id', mapped.tspmCompanyId);
    req.query('smid_company_id', mapped.smidCompanyId);
    req.query('obt_company_id', mapped.obtCompanyId);
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param apiKey
   * @param timestamp
   * @param nonce
   * @param locale
   * @param customerIp
   * @param sessionId
   * @param userAgent
   * @param authorization
   * @return Response from the API call
   */
  async getErrors(
    apiKey: string,
    timestamp: string,
    nonce: string,
    locale: string,
    customerIp: string,
    sessionId: string,
    userAgent: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/get_errors');
    const mapped = req.prepareArgs({
      apiKey: [apiKey, string()],
      timestamp: [timestamp, string()],
      nonce: [nonce, string()],
      locale: [locale, string()],
      customerIp: [customerIp, string()],
      sessionId: [sessionId, string()],
      userAgent: [userAgent, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.query('api_key', mapped.apiKey);
    req.query('timestamp', mapped.timestamp);
    req.query('nonce', mapped.nonce);
    req.query('locale', mapped.locale);
    req.query('customer_ip', mapped.customerIp);
    req.query('session_id', mapped.sessionId);
    req.query('user_agent', mapped.userAgent);
    req.authenticate(false);
    return req.call(requestOptions);
  }
}
