/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Address33 {
  address1: string;
  addressCountryCode: string;
  addressLocality: string;
  postalCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const address33Schema: Schema<Address33> = typedExpandoObject(
  {
    address1: ['address1', string()],
    addressCountryCode: ['addressCountryCode', string()],
    addressLocality: ['addressLocality', string()],
    postalCode: ['postalCode', string()],
  },
  'additionalProperties',
  optional(unknown())
);
