/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Address5 {
  address1: string;
  countryCode: string;
  city: string;
  postalCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const address5Schema: Schema<Address5> = typedExpandoObject(
  {
    address1: ['address1', string()],
    countryCode: ['countryCode', string()],
    city: ['city', string()],
    postalCode: ['postalCode', string()],
  },
  'additionalProperties',
  optional(unknown())
);
