/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Address32 {
  addressCountryCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const address32Schema: Schema<Address32> = typedExpandoObject(
  { addressCountryCode: ['addressCountryCode', string()] },
  'additionalProperties',
  optional(unknown())
);
