/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Address {
  countryCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const addressSchema: Schema<Address> = typedExpandoObject(
  { countryCode: ['countryCode', string()] },
  'additionalProperties',
  optional(unknown())
);
