/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Taxis1, taxis1Schema } from './taxis1.js';
import { Ticket, ticketSchema } from './ticket.js';

export interface Air {
  id: string;
  taxes: Taxis1[];
  tickets: Ticket[];
  additionalProperties?: Record<string, unknown>;
}

export const airSchema: Schema<Air> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      taxes: ['taxes', array(taxis1Schema)],
      tickets: ['tickets', array(ticketSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
