/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Taxis1, taxis1Schema } from './taxis1.js';
import { Ticket32, ticket32Schema } from './ticket32.js';

export interface Air16 {
  taxes: Taxis1[];
  tickets: Ticket32[];
  additionalProperties?: Record<string, unknown>;
}

export const air16Schema: Schema<Air16> = lazy(() =>
  typedExpandoObject(
    {
      taxes: ['taxes', array(taxis1Schema)],
      tickets: ['tickets', array(ticket32Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
