/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Taxis4, taxis4Schema } from './taxis4.js';
import { Ticket2, ticket2Schema } from './ticket2.js';

export interface Air1 {
  id: string;
  taxes: Taxis4[];
  tickets: Ticket2[];
  additionalProperties?: Record<string, unknown>;
}

export const air1Schema: Schema<Air1> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      taxes: ['taxes', array(taxis4Schema)],
      tickets: ['tickets', array(ticket2Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
