/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Taxis1, taxis1Schema } from './taxis1.js';
import { Ticket4, ticket4Schema } from './ticket4.js';

export interface Air2 {
  id: string;
  taxes: Taxis1[];
  tickets: Ticket4[];
  additionalProperties?: Record<string, unknown>;
}

export const air2Schema: Schema<Air2> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      taxes: ['taxes', array(taxis1Schema)],
      tickets: ['tickets', array(ticket4Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
