/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  OriginDestination,
  originDestinationSchema,
} from './originDestination.js';

export interface Airavailabilityrequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  system: string;
  configurationId: number;
  originDestinations: OriginDestination[];
  additionalProperties?: Record<string, unknown>;
}

export const airavailabilityrequestSchema: Schema<Airavailabilityrequest> = lazy(
  () =>
    typedExpandoObject(
      {
        apiKey: ['api_key', string()],
        timestamp: ['timestamp', string()],
        nonce: ['nonce', string()],
        locale: ['locale', string()],
        customerIp: ['customer_ip', string()],
        sessionId: ['session_id', string()],
        userAgent: ['user_agent', string()],
        system: ['system', string()],
        configurationId: ['configuration_id', number()],
        originDestinations: [
          'origin_destinations',
          array(originDestinationSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
