/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema, string } from '../schema.js';
import { BillingAddress, billingAddressSchema } from './billingAddress.js';
import { Traveler4, traveler4Schema } from './traveler4.js';

export interface Airbookrequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  system: string;
  booktrackId: string;
  configurationId: number;
  pnrId: string;
  fareGroupKey: string;
  flightOptionKeys: string[];
  optionalServiceKeys: string[];
  bookerEmail: string;
  bookerFirstName: string;
  bookerLastName: string;
  paymentMethod: string;
  creditCardNumber: string;
  creditCardExpirationYear: string;
  creditCardExpirationMonth: string;
  creditCardFirstName: string;
  creditCardLastName: string;
  creditCardIdentifier: string;
  billingAddress: BillingAddress;
  phoneNumber: string;
  travelers: Traveler4[];
  tspmCompanyId: string;
}

export const airbookrequestSchema: Schema<Airbookrequest> = lazy(() =>
  object({
    apiKey: ['api_key', string()],
    timestamp: ['timestamp', string()],
    nonce: ['nonce', string()],
    locale: ['locale', string()],
    customerIp: ['customer_ip', string()],
    sessionId: ['session_id', string()],
    userAgent: ['user_agent', string()],
    system: ['system', string()],
    booktrackId: ['booktrack_id', string()],
    configurationId: ['configuration_id', number()],
    pnrId: ['pnr_id', string()],
    fareGroupKey: ['fare_group_key', string()],
    flightOptionKeys: ['flight_option_keys', array(string())],
    optionalServiceKeys: ['optional_service_keys', array(string())],
    bookerEmail: ['booker_email', string()],
    bookerFirstName: ['booker_first_name', string()],
    bookerLastName: ['booker_last_name', string()],
    paymentMethod: ['payment_method', string()],
    creditCardNumber: ['credit_card_number', string()],
    creditCardExpirationYear: ['credit_card_expiration_year', string()],
    creditCardExpirationMonth: ['credit_card_expiration_month', string()],
    creditCardFirstName: ['credit_card_first_name', string()],
    creditCardLastName: ['credit_card_last_name', string()],
    creditCardIdentifier: ['credit_card_identifier', string()],
    billingAddress: ['billing_address', billingAddressSchema],
    phoneNumber: ['phone_number', string()],
    travelers: ['travelers', array(traveler4Schema)],
    tspmCompanyId: ['tspm_company_id', string()],
  })
);
