/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface AircompleteVerificationRequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  system: string;
  verificationId: string;
}

export const aircompleteVerificationRequestSchema: Schema<AircompleteVerificationRequest> = object(
  {
    apiKey: ['api_key', string()],
    timestamp: ['timestamp', string()],
    nonce: ['nonce', string()],
    locale: ['locale', string()],
    customerIp: ['customer_ip', string()],
    sessionId: ['session_id', string()],
    userAgent: ['user_agent', string()],
    system: ['system', string()],
    verificationId: ['verification_id', string()],
  }
);
