/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { Options, optionsSchema } from './options.js';

export interface AircancelReservationRequest4 {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  system: string;
  email: string;
  options: Options;
  bookingUid: string;
}

export const aircancelReservationRequest4Schema: Schema<AircancelReservationRequest4> = lazy(
  () =>
    object({
      apiKey: ['api_key', string()],
      timestamp: ['timestamp', string()],
      nonce: ['nonce', string()],
      locale: ['locale', string()],
      customerIp: ['customer_ip', string()],
      sessionId: ['session_id', string()],
      userAgent: ['user_agent', string()],
      system: ['system', string()],
      email: ['email', string()],
      options: ['options', optionsSchema],
      bookingUid: ['booking_uid', string()],
    })
);
