/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AircancelReservationrefundquoteconfirmrequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  system: string;
  email: string;
  refundQuoteId: string;
  bookingUid: string;
  additionalProperties?: Record<string, unknown>;
}

export const aircancelReservationrefundquoteconfirmrequestSchema: Schema<AircancelReservationrefundquoteconfirmrequest> = typedExpandoObject(
  {
    apiKey: ['api_key', string()],
    timestamp: ['timestamp', string()],
    nonce: ['nonce', string()],
    locale: ['locale', string()],
    customerIp: ['customer_ip', string()],
    sessionId: ['session_id', string()],
    userAgent: ['user_agent', string()],
    system: ['system', string()],
    email: ['email', string()],
    refundQuoteId: ['refund_quote_id', string()],
    bookingUid: ['booking_uid', string()],
  },
  'additionalProperties',
  optional(unknown())
);
