/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema.js';

export interface AirdocumentsIssueRequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  system: string;
  bookingUid: string;
  issueTickets: boolean;
  issueEmds: boolean;
}

export const airdocumentsIssueRequestSchema: Schema<AirdocumentsIssueRequest> = object(
  {
    apiKey: ['api_key', string()],
    timestamp: ['timestamp', string()],
    nonce: ['nonce', string()],
    locale: ['locale', string()],
    customerIp: ['customer_ip', string()],
    sessionId: ['session_id', string()],
    userAgent: ['user_agent', string()],
    system: ['system', string()],
    bookingUid: ['booking_uid', string()],
    issueTickets: ['issue_tickets', boolean()],
    issueEmds: ['issue_emds', boolean()],
  }
);
