/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  OriginDestination1,
  originDestination1Schema,
} from './originDestination1.js';
import { Traveler, travelerSchema } from './traveler.js';

export interface AirfareSearchRequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  system: string;
  configurationId: number;
  currency: string;
  airlineCodes: string[];
  travelers: Traveler[];
  originDestinations: OriginDestination1[];
  includedBaggage: boolean;
  changeableOnly: boolean;
  refundableOnly: boolean;
  excludePenalties: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const airfareSearchRequestSchema: Schema<AirfareSearchRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        apiKey: ['api_key', string()],
        timestamp: ['timestamp', string()],
        nonce: ['nonce', string()],
        locale: ['locale', string()],
        customerIp: ['customer_ip', string()],
        sessionId: ['session_id', string()],
        userAgent: ['user_agent', string()],
        system: ['system', string()],
        configurationId: ['configuration_id', number()],
        currency: ['currency', string()],
        airlineCodes: ['airline_codes', array(string())],
        travelers: ['travelers', array(travelerSchema)],
        originDestinations: [
          'origin_destinations',
          array(originDestination1Schema),
        ],
        includedBaggage: ['included_baggage', boolean()],
        changeableOnly: ['changeable_only', boolean()],
        refundableOnly: ['refundable_only', boolean()],
        excludePenalties: ['exclude_penalties', boolean()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
