/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface AirgetCheckoutDataRequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  system: string;
  configurationId: number;
  fareGroupKey: string;
  tspmTravelerId: string;
  tspmCompanyId: string;
}

export const airgetCheckoutDataRequestSchema: Schema<AirgetCheckoutDataRequest> = object(
  {
    apiKey: ['api_key', string()],
    timestamp: ['timestamp', string()],
    nonce: ['nonce', string()],
    locale: ['locale', string()],
    customerIp: ['customer_ip', string()],
    sessionId: ['session_id', string()],
    userAgent: ['user_agent', string()],
    system: ['system', string()],
    configurationId: ['configuration_id', number()],
    fareGroupKey: ['fare_group_key', string()],
    tspmTravelerId: ['tspm_traveler_id', string()],
    tspmCompanyId: ['tspm_company_id', string()],
  }
);
