/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  Schema,
  string,
} from '../schema.js';
import { Traveler, travelerSchema } from './traveler.js';

export interface AirpricingfareSearchrequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  system: string;
  configurationId: number;
  currency: string;
  fareGroupKey: string;
  flightOptionKeys: string[];
  optionalServiceKeys: string[];
  fareFamilies: boolean;
  travelers: Traveler[];
}

export const airpricingfareSearchrequestSchema: Schema<AirpricingfareSearchrequest> = lazy(
  () =>
    object({
      apiKey: ['api_key', string()],
      timestamp: ['timestamp', string()],
      nonce: ['nonce', string()],
      locale: ['locale', string()],
      customerIp: ['customer_ip', string()],
      sessionId: ['session_id', string()],
      userAgent: ['user_agent', string()],
      system: ['system', string()],
      configurationId: ['configuration_id', number()],
      currency: ['currency', string()],
      fareGroupKey: ['fare_group_key', string()],
      flightOptionKeys: ['flight_option_keys', array(string())],
      optionalServiceKeys: ['optional_service_keys', array(string())],
      fareFamilies: ['fare_families', boolean()],
      travelers: ['travelers', array(travelerSchema)],
    })
);
