/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface AirretrieveReservationsListRequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  system: string;
  travelerEmail: string;
  limit: number;
  offset: number;
  currency: string;
}

export const airretrieveReservationsListRequestSchema: Schema<AirretrieveReservationsListRequest> = object(
  {
    apiKey: ['api_key', string()],
    timestamp: ['timestamp', string()],
    nonce: ['nonce', string()],
    locale: ['locale', string()],
    customerIp: ['customer_ip', string()],
    sessionId: ['session_id', string()],
    userAgent: ['user_agent', string()],
    system: ['system', string()],
    travelerEmail: ['traveler_email', string()],
    limit: ['limit', number()],
    offset: ['offset', number()],
    currency: ['currency', string()],
  }
);
