/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema, string } from '../schema.js';
import { Traveler3, traveler3Schema } from './traveler3.js';

export interface AirseatMapRequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  system: string;
  configurationId: number;
  fareGroupKey: string;
  flightOptionKeys: string[];
  traveler: Traveler3;
}

export const airseatMapRequestSchema: Schema<AirseatMapRequest> = lazy(() =>
  object({
    apiKey: ['api_key', string()],
    timestamp: ['timestamp', string()],
    nonce: ['nonce', string()],
    locale: ['locale', string()],
    customerIp: ['customer_ip', string()],
    sessionId: ['session_id', string()],
    userAgent: ['user_agent', string()],
    system: ['system', string()],
    configurationId: ['configuration_id', number()],
    fareGroupKey: ['fare_group_key', string()],
    flightOptionKeys: ['flight_option_keys', array(string())],
    traveler: ['traveler', traveler3Schema],
  })
);
