/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ArrivalLocation {
  locationCode: string;
  locationType: string;
  additionalProperties?: Record<string, unknown>;
}

export const arrivalLocationSchema: Schema<ArrivalLocation> = typedExpandoObject(
  {
    locationCode: ['location_code', string()],
    locationType: ['location_type', string()],
  },
  'additionalProperties',
  optional(unknown())
);
