/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface ArrivalLocation {
  locationCode: string;
  locationType: string;
}

export const arrivalLocationSchema: Schema<ArrivalLocation> = object({
  locationCode: ['location_code', string()],
  locationType: ['location_type', string()],
});
