/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  BaseFare1Amount,
  baseFare1AmountSchema,
} from './containers/baseFare1Amount.js';

export interface BaseFare1 {
  amount: BaseFare1Amount;
  currencyCode: string;
  description: string;
  additionalProperties?: Record<string, unknown>;
}

export const baseFare1Schema: Schema<BaseFare1> = lazy(() =>
  typedExpandoObject(
    {
      amount: ['amount', baseFare1AmountSchema],
      currencyCode: ['currencyCode', string()],
      description: ['description', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
