/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BillingAddress {
  city: string;
  countryCode: string;
  postalCode: string;
  stateCode: string;
  streetAddress1: string;
  additionalProperties?: Record<string, unknown>;
}

export const billingAddressSchema: Schema<BillingAddress> = typedExpandoObject(
  {
    city: ['city', string()],
    countryCode: ['country_code', string()],
    postalCode: ['postal_code', string()],
    stateCode: ['state_code', string()],
    streetAddress1: ['street_address1', string()],
  },
  'additionalProperties',
  optional(unknown())
);
