/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface BillingAddress {
  city: string;
  countryCode: string;
  postalCode: string;
  stateCode: string;
  streetAddress1: string;
}

export const billingAddressSchema: Schema<BillingAddress> = object({
  city: ['city', string()],
  countryCode: ['country_code', string()],
  postalCode: ['postal_code', string()],
  stateCode: ['state_code', string()],
  streetAddress1: ['street_address1', string()],
});
