/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema } from '../schema.js';

export interface BookingData {
  isGhost: boolean;
}

export const bookingDataSchema: Schema<BookingData> = object({
  isGhost: ['is_ghost', boolean()],
});
