/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BookingData {
  isGhost: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const bookingDataSchema: Schema<BookingData> = typedExpandoObject(
  { isGhost: ['is_ghost', boolean()] },
  'additionalProperties',
  optional(unknown())
);
