/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Location, locationSchema } from './location.js';

export interface Broker {
  name: string;
  location: Location;
  additionalProperties?: Record<string, unknown>;
}

export const brokerSchema: Schema<Broker> = lazy(() =>
  typedExpandoObject(
    { name: ['name', string()], location: ['location', locationSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
