/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Location16, location16Schema } from './location16.js';

export interface Broker16 {
  name: string;
  location: Location16;
  additionalProperties?: Record<string, unknown>;
}

export const broker16Schema: Schema<Broker16> = lazy(() =>
  typedExpandoObject(
    { name: ['name', string()], location: ['location', location16Schema] },
    'additionalProperties',
    optional(unknown())
  )
);
