/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Reservation, reservationSchema } from './reservation.js';

export interface Car {
  id: string;
  reservations: Reservation[];
  additionalProperties?: Record<string, unknown>;
}

export const carSchema: Schema<Car> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      reservations: ['reservations', array(reservationSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
