/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Reservation56, reservation56Schema } from './reservation56.js';

export interface Car16 {
  reservations: Reservation56[];
  additionalProperties?: Record<string, unknown>;
}

export const car16Schema: Schema<Car16> = lazy(() =>
  typedExpandoObject(
    { reservations: ['reservations', array(reservation56Schema)] },
    'additionalProperties',
    optional(unknown())
  )
);
