/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Reservation4, reservation4Schema } from './reservation4.js';

export interface Car1 {
  id: string;
  reservations: Reservation4[];
  additionalProperties?: Record<string, unknown>;
}

export const car1Schema: Schema<Car1> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      reservations: ['reservations', array(reservation4Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
