/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Reservation8, reservation8Schema } from './reservation8.js';

export interface Car2 {
  id: string;
  reservations: Reservation8[];
  additionalProperties?: Record<string, unknown>;
}

export const car2Schema: Schema<Car2> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      reservations: ['reservations', array(reservation8Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
