/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CardDetail {
  type: string;
  number: string;
  additionalProperties?: Record<string, unknown>;
}

export const cardDetailSchema: Schema<CardDetail> = typedExpandoObject(
  { type: ['type', string()], number: ['number', string()] },
  'additionalProperties',
  optional(unknown())
);
