/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CarsmodifyReservationRequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  configurationId: number;
  system: string;
  bookingUid: string;
  flightNumber: string;
  specialEquipment: string[];
  specialInformation: string;
  pickupDatetime: string;
  dropoffDatetime: string;
  carType: string;
  additionalProperties?: Record<string, unknown>;
}

export const carsmodifyReservationRequestSchema: Schema<CarsmodifyReservationRequest> = typedExpandoObject(
  {
    apiKey: ['api_key', string()],
    timestamp: ['timestamp', string()],
    nonce: ['nonce', string()],
    locale: ['locale', string()],
    customerIp: ['customer_ip', string()],
    sessionId: ['session_id', string()],
    userAgent: ['user_agent', string()],
    configurationId: ['configuration_id', number()],
    system: ['system', string()],
    bookingUid: ['booking_uid', string()],
    flightNumber: ['flight_number', string()],
    specialEquipment: ['special_equipment', array(string())],
    specialInformation: ['special_information', string()],
    pickupDatetime: ['pickup_datetime', string()],
    dropoffDatetime: ['dropoff_datetime', string()],
    carType: ['car_type', string()],
  },
  'additionalProperties',
  optional(unknown())
);
