/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CarsretrieveReservationsListRequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  system: string;
  travelerEmail: string;
  limit: number;
  offset: number;
  filters?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const carsretrieveReservationsListRequestSchema: Schema<CarsretrieveReservationsListRequest> = typedExpandoObject(
  {
    apiKey: ['api_key', string()],
    timestamp: ['timestamp', string()],
    nonce: ['nonce', string()],
    locale: ['locale', string()],
    customerIp: ['customer_ip', string()],
    sessionId: ['session_id', string()],
    userAgent: ['user_agent', string()],
    system: ['system', string()],
    travelerEmail: ['traveler_email', string()],
    limit: ['limit', number()],
    offset: ['offset', number()],
    filters: ['filters', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
