/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface Carsbookguaranteerequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  configurationId: number;
  system: string;
  booktrackId: string;
  rateKey: string;
  bookerEmail: string;
  bookerFirstName: string;
  bookerLastName: string;
  travelerEmail: string;
  travelerFirstName: string;
  travelerLastName: string;
  specialInformation: string;
}

export const carsbookguaranteerequestSchema: Schema<Carsbookguaranteerequest> = object(
  {
    apiKey: ['api_key', string()],
    timestamp: ['timestamp', string()],
    nonce: ['nonce', string()],
    locale: ['locale', string()],
    customerIp: ['customer_ip', string()],
    sessionId: ['session_id', string()],
    userAgent: ['user_agent', string()],
    configurationId: ['configuration_id', number()],
    system: ['system', string()],
    booktrackId: ['booktrack_id', string()],
    rateKey: ['rate_key', string()],
    bookerEmail: ['booker_email', string()],
    bookerFirstName: ['booker_first_name', string()],
    bookerLastName: ['booker_last_name', string()],
    travelerEmail: ['traveler_email', string()],
    travelerFirstName: ['traveler_first_name', string()],
    travelerLastName: ['traveler_last_name', string()],
    specialInformation: ['special_information', string()],
  }
);
