/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CarsdirectSellBooknoPaymentrequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  configurationId: number;
  system: string;
  booktrackId: string;
  carType: string;
  vendorCode: string;
  pickupDatetime: string;
  pickupLocationKey: string;
  dropoffDatetime: string;
  dropoffLocationKey: string;
  bookerEmail: string;
  bookerFirstName: string;
  bookerLastName: string;
  pnrId: string;
  travelerEmail: string;
  travelerFirstName: string;
  travelerLastName: string;
  specialInformation: string;
  paymentMethod: string;
  additionalProperties?: Record<string, unknown>;
}

export const carsdirectSellBooknoPaymentrequestSchema: Schema<CarsdirectSellBooknoPaymentrequest> = typedExpandoObject(
  {
    apiKey: ['api_key', string()],
    timestamp: ['timestamp', string()],
    nonce: ['nonce', string()],
    locale: ['locale', string()],
    customerIp: ['customer_ip', string()],
    sessionId: ['session_id', string()],
    userAgent: ['user_agent', string()],
    configurationId: ['configuration_id', number()],
    system: ['system', string()],
    booktrackId: ['booktrack_id', string()],
    carType: ['car_type', string()],
    vendorCode: ['vendor_code', string()],
    pickupDatetime: ['pickup_datetime', string()],
    pickupLocationKey: ['pickup_location_key', string()],
    dropoffDatetime: ['dropoff_datetime', string()],
    dropoffLocationKey: ['dropoff_location_key', string()],
    bookerEmail: ['booker_email', string()],
    bookerFirstName: ['booker_first_name', string()],
    bookerLastName: ['booker_last_name', string()],
    pnrId: ['pnr_id', string()],
    travelerEmail: ['traveler_email', string()],
    travelerFirstName: ['traveler_first_name', string()],
    travelerLastName: ['traveler_last_name', string()],
    specialInformation: ['special_information', string()],
    paymentMethod: ['payment_method', string()],
  },
  'additionalProperties',
  optional(unknown())
);
