/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ClientReportableDatum {
  code: string;
  answer: string;
  additionalProperties?: Record<string, unknown>;
}

export const clientReportableDatumSchema: Schema<ClientReportableDatum> = typedExpandoObject(
  { code: ['code', string()], answer: ['answer', string()] },
  'additionalProperties',
  optional(unknown())
);
