/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface ClientReportableDatum {
  code: string;
  answer: string;
}

export const clientReportableDatumSchema: Schema<ClientReportableDatum> = object(
  { code: ['code', string()], answer: ['answer', string()] }
);
