/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Reservation2, reservation2Schema } from './reservation2.js';

export interface CruiseFerry {
  id: string;
  reservations: Reservation2[];
  additionalProperties?: Record<string, unknown>;
}

export const cruiseFerrySchema: Schema<CruiseFerry> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      reservations: ['reservations', array(reservation2Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
