/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface DepartureLocation {
  locationCode: string;
  locationType: string;
}

export const departureLocationSchema: Schema<DepartureLocation> = object({
  locationCode: ['location_code', string()],
  locationType: ['location_type', string()],
});
