/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  DocumentLineItems,
  documentLineItemsSchema,
} from './containers/documentLineItems.js';
import { Fare, fareSchema } from './fare.js';

export interface Document {
  documentNumber: string;
  bookingType: string;
  fare: Fare;
  baseFare: Fare;
  lineItems: DocumentLineItems[];
  additionalProperties?: Record<string, unknown>;
}

export const documentSchema: Schema<Document> = lazy(() =>
  typedExpandoObject(
    {
      documentNumber: ['documentNumber', string()],
      bookingType: ['bookingType', string()],
      fare: ['fare', fareSchema],
      baseFare: ['baseFare', fareSchema],
      lineItems: ['lineItems', array(documentLineItemsSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
