/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface DropOffLocation2 {
  address1: string;
  countryCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const dropOffLocation2Schema: Schema<DropOffLocation2> = typedExpandoObject(
  { address1: ['address1', string()], countryCode: ['countryCode', string()] },
  'additionalProperties',
  optional(unknown())
);
