/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface DropOffLocation16 {
  address1: string;
  addressCountryCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const dropOffLocation16Schema: Schema<DropOffLocation16> = typedExpandoObject(
  {
    address1: ['address1', string()],
    addressCountryCode: ['addressCountryCode', string()],
  },
  'additionalProperties',
  optional(unknown())
);
