/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface DropOffLocation1 {
  address1: string;
  address2: string;
  countryCode: string;
  city: string;
  region: string;
  postalCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const dropOffLocation1Schema: Schema<DropOffLocation1> = typedExpandoObject(
  {
    address1: ['address1', string()],
    address2: ['address2', string()],
    countryCode: ['countryCode', string()],
    city: ['city', string()],
    region: ['region', string()],
    postalCode: ['postalCode', string()],
  },
  'additionalProperties',
  optional(unknown())
);
