/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Fare2Amount, fare2AmountSchema } from './containers/fare2Amount.js';

export interface Fare2 {
  amount: Fare2Amount;
  currencyCode: string;
  description: string;
  additionalProperties?: Record<string, unknown>;
}

export const fare2Schema: Schema<Fare2> = lazy(() =>
  typedExpandoObject(
    {
      amount: ['amount', fare2AmountSchema],
      currencyCode: ['currencyCode', string()],
      description: ['description', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
