/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Fare {
  amount: number;
  currencyCode: string;
  description: string;
  additionalProperties?: Record<string, unknown>;
}

export const fareSchema: Schema<Fare> = typedExpandoObject(
  {
    amount: ['amount', number()],
    currencyCode: ['currencyCode', string()],
    description: ['description', string()],
  },
  'additionalProperties',
  optional(unknown())
);
