/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Fare3Amount, fare3AmountSchema } from './containers/fare3Amount.js';

export interface Fare3 {
  amount: Fare3Amount;
  currencyCode: string;
  description: string;
  additionalProperties?: Record<string, unknown>;
}

export const fare3Schema: Schema<Fare3> = lazy(() =>
  typedExpandoObject(
    {
      amount: ['amount', fare3AmountSchema],
      currencyCode: ['currencyCode', string()],
      description: ['description', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
