/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface FfNumber {
  airlineCode: string;
  ffNumber: string;
}

export const ffNumberSchema: Schema<FfNumber> = object({
  airlineCode: ['airline_code', string()],
  ffNumber: ['ff_number', string()],
});
