/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface FfNumber {
  airlineCode: string;
  ffNumber: string;
  additionalProperties?: Record<string, unknown>;
}

export const ffNumberSchema: Schema<FfNumber> = typedExpandoObject(
  {
    airlineCode: ['airline_code', string()],
    ffNumber: ['ff_number', string()],
  },
  'additionalProperties',
  optional(unknown())
);
