/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Filter1 {
  recordLocator: string[];
  additionalProperties?: Record<string, unknown>;
}

export const filter1Schema: Schema<Filter1> = typedExpandoObject(
  { recordLocator: ['recordLocator', array(string())] },
  'additionalProperties',
  optional(unknown())
);
