/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Filter10 {
  accountId: string[];
  additionalProperties?: Record<string, unknown>;
}

export const filter10Schema: Schema<Filter10> = typedExpandoObject(
  { accountId: ['accountId', array(string())] },
  'additionalProperties',
  optional(unknown())
);
