/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Filter14 {
  calculatedTicketStatus: string[];
  additionalProperties?: Record<string, unknown>;
}

export const filter14Schema: Schema<Filter14> = typedExpandoObject(
  { calculatedTicketStatus: ['calculatedTicketStatus', array(string())] },
  'additionalProperties',
  optional(unknown())
);
