/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Filter8 {
  lastModifiedDateTime: string;
  additionalProperties?: Record<string, unknown>;
}

export const filter8Schema: Schema<Filter8> = typedExpandoObject(
  { lastModifiedDateTime: ['lastModifiedDateTime', string()] },
  'additionalProperties',
  optional(unknown())
);
