/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Filter15 {
  hasTransaction: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const filter15Schema: Schema<Filter15> = typedExpandoObject(
  { hasTransaction: ['hasTransaction', boolean()] },
  'additionalProperties',
  optional(unknown())
);
