/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Filter6 {
  invoiceDateTime: string;
  additionalProperties?: Record<string, unknown>;
}

export const filter6Schema: Schema<Filter6> = typedExpandoObject(
  { invoiceDateTime: ['invoiceDateTime', string()] },
  'additionalProperties',
  optional(unknown())
);
