/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Filter13 {
  ticketStatus: string[];
  additionalProperties?: Record<string, unknown>;
}

export const filter13Schema: Schema<Filter13> = typedExpandoObject(
  { ticketStatus: ['ticketStatus', array(string())] },
  'additionalProperties',
  optional(unknown())
);
