/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Filter12 {
  customerNumber: string[];
  additionalProperties?: Record<string, unknown>;
}

export const filter12Schema: Schema<Filter12> = typedExpandoObject(
  { customerNumber: ['customerNumber', array(string())] },
  'additionalProperties',
  optional(unknown())
);
