/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Filter4 {
  bookingDateTime: string;
  additionalProperties?: Record<string, unknown>;
}

export const filter4Schema: Schema<Filter4> = typedExpandoObject(
  { bookingDateTime: ['bookingDateTime', string()] },
  'additionalProperties',
  optional(unknown())
);
