/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Filter3 {
  travelerEmail: string[];
  additionalProperties?: Record<string, unknown>;
}

export const filter3Schema: Schema<Filter3> = typedExpandoObject(
  { travelerEmail: ['travelerEmail', array(string())] },
  'additionalProperties',
  optional(unknown())
);
