/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Filter {
  invoiceNumber: string[];
  travelerEmail: string[];
  bookingDateTime: string;
  invoiceDateTime: string;
  lastModifiedDateTime: string;
  customerNumber: string[];
  accountId: string[];
  globalCustomerNumber: string[];
  hasTransaction: boolean;
  recordLocator: string[];
  ticketStatus: string[];
  calculatedTicketStatus: string[];
  additionalProperties?: Record<string, unknown>;
}

export const filterSchema: Schema<Filter> = typedExpandoObject(
  {
    invoiceNumber: ['invoiceNumber', array(string())],
    travelerEmail: ['travelerEmail', array(string())],
    bookingDateTime: ['bookingDateTime', string()],
    invoiceDateTime: ['invoiceDateTime', string()],
    lastModifiedDateTime: ['lastModifiedDateTime', string()],
    customerNumber: ['customerNumber', array(string())],
    accountId: ['accountId', array(string())],
    globalCustomerNumber: ['globalCustomerNumber', array(string())],
    hasTransaction: ['hasTransaction', boolean()],
    recordLocator: ['recordLocator', array(string())],
    ticketStatus: ['ticketStatus', array(string())],
    calculatedTicketStatus: ['calculatedTicketStatus', array(string())],
  },
  'additionalProperties',
  optional(unknown())
);
