/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Filter2 {
  invoiceNumber: string[];
  additionalProperties?: Record<string, unknown>;
}

export const filter2Schema: Schema<Filter2> = typedExpandoObject(
  { invoiceNumber: ['invoiceNumber', array(string())] },
  'additionalProperties',
  optional(unknown())
);
