/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Filter11 {
  globalCustomerNumber: string[];
  additionalProperties?: Record<string, unknown>;
}

export const filter11Schema: Schema<Filter11> = typedExpandoObject(
  { globalCustomerNumber: ['globalCustomerNumber', array(string())] },
  'additionalProperties',
  optional(unknown())
);
