/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface GenerateOauth20Token {
  accessToken: string;
  expiresIn: number;
  tokenType: string;
  additionalProperties?: Record<string, unknown>;
}

export const generateOauth20TokenSchema: Schema<GenerateOauth20Token> = typedExpandoObject(
  {
    accessToken: ['access_token', string()],
    expiresIn: ['expires_in', number()],
    tokenType: ['token_type', string()],
  },
  'additionalProperties',
  optional(unknown())
);
