/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ClientReportableDatum,
  clientReportableDatumSchema,
} from './clientReportableDatum.js';

export interface GetConfigurationsPostRequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  entityId: number;
  system: string;
  tspmCompanyId: string;
  tspmTravelerId: string;
  clientReportableData: ClientReportableDatum[];
  pnrId: string;
  additionalProperties?: Record<string, unknown>;
}

export const getConfigurationsPostRequestSchema: Schema<GetConfigurationsPostRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        apiKey: ['api_key', string()],
        timestamp: ['timestamp', string()],
        nonce: ['nonce', string()],
        locale: ['locale', string()],
        customerIp: ['customer_ip', string()],
        sessionId: ['session_id', string()],
        userAgent: ['user_agent', string()],
        entityId: ['entity_id', number()],
        system: ['system', string()],
        tspmCompanyId: ['tspm_company_id', string()],
        tspmTravelerId: ['tspm_traveler_id', string()],
        clientReportableData: [
          'client_reportable_data',
          array(clientReportableDatumSchema),
        ],
        pnrId: ['pnr_id', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
