/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Result16, result16Schema } from './result16.js';

export interface GetVersionsbytripId {
  code: number;
  status: string;
  result: Result16[];
  additionalProperties?: Record<string, unknown>;
}

export const getVersionsbytripIdSchema: Schema<GetVersionsbytripId> = lazy(() =>
  typedExpandoObject(
    {
      code: ['code', number()],
      status: ['status', string()],
      result: ['result', array(result16Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
