/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Guest {
  lastName: string;
  identifiers: string[];
  additionalProperties?: Record<string, unknown>;
}

export const guestSchema: Schema<Guest> = typedExpandoObject(
  {
    lastName: ['lastName', string()],
    identifiers: ['identifiers', array(string())],
  },
  'additionalProperties',
  optional(unknown())
);
