/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Reservation57, reservation57Schema } from './reservation57.js';

export interface Hotel16 {
  reservations: Reservation57[];
  additionalProperties?: Record<string, unknown>;
}

export const hotel16Schema: Schema<Hotel16> = lazy(() =>
  typedExpandoObject(
    { reservations: ['reservations', array(reservation57Schema)] },
    'additionalProperties',
    optional(unknown())
  )
);
