/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Reservation6, reservation6Schema } from './reservation6.js';

export interface Hotel1 {
  id: string;
  reservations: Reservation6[];
  additionalProperties?: Record<string, unknown>;
}

export const hotel1Schema: Schema<Hotel1> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      reservations: ['reservations', array(reservation6Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
