/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Reservation1, reservation1Schema } from './reservation1.js';

export interface Hotel {
  id: string;
  reservations: Reservation1[];
  additionalProperties?: Record<string, unknown>;
}

export const hotelSchema: Schema<Hotel> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      reservations: ['reservations', array(reservation1Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
