/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Reservation9, reservation9Schema } from './reservation9.js';

export interface Hotel2 {
  id: string;
  reservations: Reservation9[];
  additionalProperties?: Record<string, unknown>;
}

export const hotel2Schema: Schema<Hotel2> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      reservations: ['reservations', array(reservation9Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
