/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema, string } from '../schema.js';
import { BookingData, bookingDataSchema } from './bookingData.js';

export interface HotelsupdateReservationDetailsRequest1 {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  configurationId: number;
  system: string;
  bookingUid: string;
  bookingData: BookingData;
}

export const hotelsupdateReservationDetailsRequest1Schema: Schema<HotelsupdateReservationDetailsRequest1> = lazy(
  () =>
    object({
      apiKey: ['api_key', string()],
      timestamp: ['timestamp', string()],
      nonce: ['nonce', string()],
      locale: ['locale', string()],
      customerIp: ['customer_ip', string()],
      sessionId: ['session_id', string()],
      userAgent: ['user_agent', string()],
      configurationId: ['configuration_id', number()],
      system: ['system', string()],
      bookingUid: ['booking_uid', string()],
      bookingData: ['booking_data', bookingDataSchema],
    })
);
