/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface Hotelsbookrequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  configurationId: number;
  system: string;
  booktrackId: string;
  guestCount: number;
  hotelId: number;
  originalCurrency: string;
  originalTotal: number;
  rateKey: string;
  bookerEmail: string;
  bookerFirstName: string;
  bookerLastName: string;
  travelerEmail: string;
  travelerFirstName: string;
  travelerLastName: string;
  paymentMethod: string;
  loyaltyCardChainCode: string;
  loyaltyCardNumber: string;
  creditCardNumber: string;
  creditCardExpirationYear: string;
  creditCardExpirationMonth: string;
  creditCardFirstName: string;
  creditCardLastName: string;
  creditCardAddress: string;
  creditCardCountryCode: string;
  creditCardCity: string;
  creditCardStateProvinceCode: string;
  creditCardPostalCode: string;
  creditCardPhone: string;
}

export const hotelsbookrequestSchema: Schema<Hotelsbookrequest> = object({
  apiKey: ['api_key', string()],
  timestamp: ['timestamp', string()],
  nonce: ['nonce', string()],
  locale: ['locale', string()],
  customerIp: ['customer_ip', string()],
  sessionId: ['session_id', string()],
  userAgent: ['user_agent', string()],
  configurationId: ['configuration_id', number()],
  system: ['system', string()],
  booktrackId: ['booktrack_id', string()],
  guestCount: ['guest_count', number()],
  hotelId: ['hotel_id', number()],
  originalCurrency: ['original_currency', string()],
  originalTotal: ['original_total', number()],
  rateKey: ['rate_key', string()],
  bookerEmail: ['booker_email', string()],
  bookerFirstName: ['booker_first_name', string()],
  bookerLastName: ['booker_last_name', string()],
  travelerEmail: ['traveler_email', string()],
  travelerFirstName: ['traveler_first_name', string()],
  travelerLastName: ['traveler_last_name', string()],
  paymentMethod: ['payment_method', string()],
  loyaltyCardChainCode: ['loyalty_card_chain_code', string()],
  loyaltyCardNumber: ['loyalty_card_number', string()],
  creditCardNumber: ['credit_card_number', string()],
  creditCardExpirationYear: ['credit_card_expiration_year', string()],
  creditCardExpirationMonth: ['credit_card_expiration_month', string()],
  creditCardFirstName: ['credit_card_first_name', string()],
  creditCardLastName: ['credit_card_last_name', string()],
  creditCardAddress: ['credit_card_address', string()],
  creditCardCountryCode: ['credit_card_country_code', string()],
  creditCardCity: ['credit_card_city', string()],
  creditCardStateProvinceCode: ['credit_card_state_province_code', string()],
  creditCardPostalCode: ['credit_card_postal_code', string()],
  creditCardPhone: ['credit_card_phone', string()],
});
