/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface Hotelsrebookrequest1 {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  bookingUid: string;
  checkin: string;
  checkout: string;
  booktrackId: string;
  hotelId: number;
  originalCurrency: string;
  originalTotal: number;
  rateKey: string;
  bookerEmail: string;
  bookerFirstName: string;
  bookerLastName: string;
}

export const hotelsrebookrequest1Schema: Schema<Hotelsrebookrequest1> = object({
  apiKey: ['api_key', string()],
  timestamp: ['timestamp', string()],
  nonce: ['nonce', string()],
  locale: ['locale', string()],
  customerIp: ['customer_ip', string()],
  sessionId: ['session_id', string()],
  userAgent: ['user_agent', string()],
  bookingUid: ['booking_uid', string()],
  checkin: ['checkin', string()],
  checkout: ['checkout', string()],
  booktrackId: ['booktrack_id', string()],
  hotelId: ['hotel_id', number()],
  originalCurrency: ['original_currency', string()],
  originalTotal: ['original_total', number()],
  rateKey: ['rate_key', string()],
  bookerEmail: ['booker_email', string()],
  bookerFirstName: ['booker_first_name', string()],
  bookerLastName: ['booker_last_name', string()],
});
