/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Hotelsrebookrequest {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  bookingUid: string;
  booktrackId: string;
  hotelId: number;
  originalCurrency: string;
  originalTotal: number;
  rateKey: string;
  bookerEmail: string;
  bookerFirstName: string;
  bookerLastName: string;
  additionalProperties?: Record<string, unknown>;
}

export const hotelsrebookrequestSchema: Schema<Hotelsrebookrequest> = typedExpandoObject(
  {
    apiKey: ['api_key', string()],
    timestamp: ['timestamp', string()],
    nonce: ['nonce', string()],
    locale: ['locale', string()],
    customerIp: ['customer_ip', string()],
    sessionId: ['session_id', string()],
    userAgent: ['user_agent', string()],
    bookingUid: ['booking_uid', string()],
    booktrackId: ['booktrack_id', string()],
    hotelId: ['hotel_id', number()],
    originalCurrency: ['original_currency', string()],
    originalTotal: ['original_total', number()],
    rateKey: ['rate_key', string()],
    bookerEmail: ['booker_email', string()],
    bookerFirstName: ['booker_first_name', string()],
    bookerLastName: ['booker_last_name', string()],
  },
  'additionalProperties',
  optional(unknown())
);
