/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Leg1 {
  departureAirportCode?: string;
  departureDateTime?: string;
  arrivalAirportCode?: string;
  arrivalDateTime?: string;
  flightNumber?: string;
  segmentNumber?: number;
  classOfServiceCode?: string;
  fareBasisCode?: string;
  marketingAirlineCode?: string;
  additionalProperties?: Record<string, unknown>;
}

export const leg1Schema: Schema<Leg1> = typedExpandoObject(
  {
    departureAirportCode: ['departureAirportCode', optional(string())],
    departureDateTime: ['departureDateTime', optional(string())],
    arrivalAirportCode: ['arrivalAirportCode', optional(string())],
    arrivalDateTime: ['arrivalDateTime', optional(string())],
    flightNumber: ['flightNumber', optional(string())],
    segmentNumber: ['segmentNumber', optional(number())],
    classOfServiceCode: ['classOfServiceCode', optional(string())],
    fareBasisCode: ['fareBasisCode', optional(string())],
    marketingAirlineCode: ['marketingAirlineCode', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
