/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Leg2 {
  arrivalDateTime: string;
  arrivalStationCode: string;
  carrierCode: string;
  carrierName: string;
  departureDateTime: string;
  departureStationCode: string;
  segmentNumber: number;
  trainNumber: string;
  classOfServiceCode?: string;
  additionalProperties?: Record<string, unknown>;
}

export const leg2Schema: Schema<Leg2> = typedExpandoObject(
  {
    arrivalDateTime: ['arrivalDateTime', string()],
    arrivalStationCode: ['arrivalStationCode', string()],
    carrierCode: ['carrierCode', string()],
    carrierName: ['carrierName', string()],
    departureDateTime: ['departureDateTime', string()],
    departureStationCode: ['departureStationCode', string()],
    segmentNumber: ['segmentNumber', number()],
    trainNumber: ['trainNumber', string()],
    classOfServiceCode: ['classOfServiceCode', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
