/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Leg33 {
  departureAirportCode?: string;
  arrivalAirportCode?: string;
  flightNumber?: string;
  segmentNumber?: number;
  classOfServiceCode?: string;
  fareBasisCode?: string;
  departureDate?: string;
  arrivalDate?: string;
  additionalProperties?: Record<string, unknown>;
}

export const leg33Schema: Schema<Leg33> = typedExpandoObject(
  {
    departureAirportCode: ['departureAirportCode', optional(string())],
    arrivalAirportCode: ['arrivalAirportCode', optional(string())],
    flightNumber: ['flightNumber', optional(string())],
    segmentNumber: ['segmentNumber', optional(number())],
    classOfServiceCode: ['classOfServiceCode', optional(string())],
    fareBasisCode: ['fareBasisCode', optional(string())],
    departureDate: ['departureDate', optional(string())],
    arrivalDate: ['arrivalDate', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
