/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Leg3 {
  departureAirportCode: string;
  departureDateTime?: string;
  arrivalAirportCode: string;
  arrivalDateTime?: string;
  flightNumber: string;
  segmentNumber: number;
  marketingAirlineCode: string;
  classOfServiceCode: string;
  fareBasisCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const leg3Schema: Schema<Leg3> = typedExpandoObject(
  {
    departureAirportCode: ['departureAirportCode', string()],
    departureDateTime: ['departureDateTime', optional(string())],
    arrivalAirportCode: ['arrivalAirportCode', string()],
    arrivalDateTime: ['arrivalDateTime', optional(string())],
    flightNumber: ['flightNumber', string()],
    segmentNumber: ['segmentNumber', number()],
    marketingAirlineCode: ['marketingAirlineCode', string()],
    classOfServiceCode: ['classOfServiceCode', string()],
    fareBasisCode: ['fareBasisCode', string()],
  },
  'additionalProperties',
  optional(unknown())
);
