/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  LineItem1Total,
  lineItem1TotalSchema,
} from './containers/lineItem1Total.js';

export interface LineItem1 {
  sequenceNumber: number;
  description?: string;
  total: LineItem1Total;
  additionalProperties?: Record<string, unknown>;
}

export const lineItem1Schema: Schema<LineItem1> = lazy(() =>
  typedExpandoObject(
    {
      sequenceNumber: ['sequenceNumber', number()],
      description: ['description', optional(string())],
      total: ['total', lineItem1TotalSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
