/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  LineItemTotal,
  lineItemTotalSchema,
} from './containers/lineItemTotal.js';

export interface LineItem {
  sequenceNumber?: number;
  description?: string;
  total?: LineItemTotal;
  additionalProperties?: Record<string, unknown>;
}

export const lineItemSchema: Schema<LineItem> = lazy(() =>
  typedExpandoObject(
    {
      sequenceNumber: ['sequenceNumber', optional(number())],
      description: ['description', optional(string())],
      total: ['total', optional(lineItemTotalSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
