/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Address32, address32Schema } from './address32.js';

export interface Location16 {
  address: Address32;
  additionalProperties?: Record<string, unknown>;
}

export const location16Schema: Schema<Location16> = lazy(() =>
  typedExpandoObject(
    { address: ['address', address32Schema] },
    'additionalProperties',
    optional(unknown())
  )
);
