/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Address, addressSchema } from './address.js';

export interface Location {
  address: Address;
  additionalProperties?: Record<string, unknown>;
}

export const locationSchema: Schema<Location> = lazy(() =>
  typedExpandoObject(
    { address: ['address', addressSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
