/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Document, documentSchema } from './document.js';

export interface Misc10 {
  documents: Document[];
  additionalProperties?: Record<string, unknown>;
}

export const misc10Schema: Schema<Misc10> = lazy(() =>
  typedExpandoObject(
    { documents: ['documents', array(documentSchema)] },
    'additionalProperties',
    optional(unknown())
  )
);
