/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Document, documentSchema } from './document.js';

export interface Misc {
  id: string;
  documents: Document[];
  additionalProperties?: Record<string, unknown>;
}

export const miscSchema: Schema<Misc> = lazy(() =>
  typedExpandoObject(
    { id: ['id', string()], documents: ['documents', array(documentSchema)] },
    'additionalProperties',
    optional(unknown())
  )
);
