/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Options {
  requestQuoteId: boolean;
  segmentsOnly: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const optionsSchema: Schema<Options> = typedExpandoObject(
  {
    requestQuoteId: ['request_quote_id', boolean()],
    segmentsOnly: ['segments_only', boolean()],
  },
  'additionalProperties',
  optional(unknown())
);
