/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema } from '../schema.js';

export interface Options {
  requestQuoteId: boolean;
  segmentsOnly: boolean;
}

export const optionsSchema: Schema<Options> = object({
  requestQuoteId: ['request_quote_id', boolean()],
  segmentsOnly: ['segments_only', boolean()],
});
