/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema.js';
import {
  DepartureLocation,
  departureLocationSchema,
} from './departureLocation.js';
import { SpecificFlight, specificFlightSchema } from './specificFlight.js';
import { TimeRestriction, timeRestrictionSchema } from './timeRestriction.js';

export interface OriginDestination {
  departureDate: string;
  departureLocation: DepartureLocation;
  arrivalLocation: DepartureLocation;
  specificFlights: SpecificFlight[];
  airlineCodes: string[];
  timeRestriction: TimeRestriction;
}

export const originDestinationSchema: Schema<OriginDestination> = lazy(() =>
  object({
    departureDate: ['departure_date', string()],
    departureLocation: ['departure_location', departureLocationSchema],
    arrivalLocation: ['arrival_location', departureLocationSchema],
    specificFlights: ['specific_flights', array(specificFlightSchema)],
    airlineCodes: ['airline_codes', array(string())],
    timeRestriction: ['time_restriction', timeRestrictionSchema],
  })
);
