/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  DepartureLocation,
  departureLocationSchema,
} from './departureLocation.js';
import { TimeRestriction, timeRestrictionSchema } from './timeRestriction.js';

export interface OriginDestination1 {
  departureDate: string;
  departureLocation: DepartureLocation;
  arrivalLocation: DepartureLocation;
  timeRestriction?: TimeRestriction;
  additionalProperties?: Record<string, unknown>;
}

export const originDestination1Schema: Schema<OriginDestination1> = lazy(() =>
  typedExpandoObject(
    {
      departureDate: ['departure_date', string()],
      departureLocation: ['departure_location', departureLocationSchema],
      arrivalLocation: ['arrival_location', departureLocationSchema],
      timeRestriction: ['time_restriction', optional(timeRestrictionSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
