/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  DepartureLocation,
  departureLocationSchema,
} from './departureLocation.js';
import { SpecificFlight, specificFlightSchema } from './specificFlight.js';
import { TimeRestriction, timeRestrictionSchema } from './timeRestriction.js';

export interface OriginDestination {
  departureDate: string;
  departureLocation: DepartureLocation;
  arrivalLocation: DepartureLocation;
  specificFlights: SpecificFlight[];
  airlineCodes: string[];
  timeRestriction: TimeRestriction;
  additionalProperties?: Record<string, unknown>;
}

export const originDestinationSchema: Schema<OriginDestination> = lazy(() =>
  typedExpandoObject(
    {
      departureDate: ['departure_date', string()],
      departureLocation: ['departure_location', departureLocationSchema],
      arrivalLocation: ['arrival_location', departureLocationSchema],
      specificFlights: ['specific_flights', array(specificFlightSchema)],
      airlineCodes: ['airline_codes', array(string())],
      timeRestriction: ['time_restriction', timeRestrictionSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
