/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  DepartureLocation,
  departureLocationSchema,
} from './departureLocation.js';
import { TimeRestriction, timeRestrictionSchema } from './timeRestriction.js';

export interface OriginDestination1 {
  departureDate: string;
  departureLocation: DepartureLocation;
  arrivalLocation: DepartureLocation;
  timeRestriction?: TimeRestriction;
}

export const originDestination1Schema: Schema<OriginDestination1> = lazy(() =>
  object({
    departureDate: ['departure_date', string()],
    departureLocation: ['departure_location', departureLocationSchema],
    arrivalLocation: ['arrival_location', departureLocationSchema],
    timeRestriction: ['time_restriction', optional(timeRestrictionSchema)],
  })
);
