/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Passport {
  countryOfIssue: string;
  expiryDate: string;
  nationality: string;
  number: string;
  additionalProperties?: Record<string, unknown>;
}

export const passportSchema: Schema<Passport> = typedExpandoObject(
  {
    countryOfIssue: ['country_of_issue', string()],
    expiryDate: ['expiry_date', string()],
    nationality: ['nationality', string()],
    number: ['number', string()],
  },
  'additionalProperties',
  optional(unknown())
);
