/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface Passport {
  countryOfIssue: string;
  expiryDate: string;
  nationality: string;
  number: string;
}

export const passportSchema: Schema<Passport> = object({
  countryOfIssue: ['country_of_issue', string()],
  expiryDate: ['expiry_date', string()],
  nationality: ['nationality', string()],
  number: ['number', string()],
});
