/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CardDetail, cardDetailSchema } from './cardDetail.js';

export interface Payment3 {
  amount: number;
  paymentType: string;
  currencyCode: string;
  cardDetail: CardDetail;
  authorizationCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const payment3Schema: Schema<Payment3> = lazy(() =>
  typedExpandoObject(
    {
      amount: ['amount', number()],
      paymentType: ['paymentType', string()],
      currencyCode: ['currencyCode', string()],
      cardDetail: ['cardDetail', cardDetailSchema],
      authorizationCode: ['authorizationCode', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
