/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CardDetail, cardDetailSchema } from './cardDetail.js';

export interface Payment1 {
  amount?: number;
  paymentType: string;
  currencyCode?: string;
  cardDetail?: CardDetail;
  authorizationCode?: string;
  ticketNumber?: string;
  additionalProperties?: Record<string, unknown>;
}

export const payment1Schema: Schema<Payment1> = lazy(() =>
  typedExpandoObject(
    {
      amount: ['amount', optional(number())],
      paymentType: ['paymentType', string()],
      currencyCode: ['currencyCode', optional(string())],
      cardDetail: ['cardDetail', optional(cardDetailSchema)],
      authorizationCode: ['authorizationCode', optional(string())],
      ticketNumber: ['ticketNumber', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
