/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PickupLocation {
  address1: string;
  countryCode: string;
  address2?: string;
  city?: string;
  region?: string;
  postalCode?: string;
  additionalProperties?: Record<string, unknown>;
}

export const pickupLocationSchema: Schema<PickupLocation> = typedExpandoObject(
  {
    address1: ['address1', string()],
    countryCode: ['countryCode', string()],
    address2: ['address2', optional(string())],
    city: ['city', optional(string())],
    region: ['region', optional(string())],
    postalCode: ['postalCode', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
