/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface Pingrequest2 {
  apiKey: string;
  timestamp: string;
  nonce: string;
  locale: string;
  customerIp: string;
  sessionId: string;
  userAgent: string;
  configurationId: number;
  system: string;
}

export const pingrequest2Schema: Schema<Pingrequest2> = object({
  apiKey: ['api_key', string()],
  timestamp: ['timestamp', string()],
  nonce: ['nonce', string()],
  locale: ['locale', string()],
  customerIp: ['customer_ip', string()],
  sessionId: ['session_id', string()],
  userAgent: ['user_agent', string()],
  configurationId: ['configuration_id', number()],
  system: ['system', string()],
});
