/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface PingGETRESPONSE {
  ping: string;
}

export const pingGETRESPONSESchema: Schema<PingGETRESPONSE> = object({
  ping: ['ping', string()],
});
