/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PingGetresponse {
  ping: string;
  additionalProperties?: Record<string, unknown>;
}

export const pingGetresponseSchema: Schema<PingGetresponse> = typedExpandoObject(
  { ping: ['ping', string()] },
  'additionalProperties',
  optional(unknown())
);
