/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Air1, air1Schema } from './air1.js';
import { Car1, car1Schema } from './car1.js';
import { CruiseFerry, cruiseFerrySchema } from './cruiseFerry.js';
import { Hotel1, hotel1Schema } from './hotel1.js';
import { Rail1, rail1Schema } from './rail1.js';
import { Tour, tourSchema } from './tour.js';

export interface Products1 {
  air: Air1;
  car: Car1;
  cruiseFerry: CruiseFerry;
  hotel: Hotel1;
  rail: Rail1;
  tour: Tour;
  additionalProperties?: Record<string, unknown>;
}

export const products1Schema: Schema<Products1> = lazy(() =>
  typedExpandoObject(
    {
      air: ['air', air1Schema],
      car: ['car', car1Schema],
      cruiseFerry: ['cruiseFerry', cruiseFerrySchema],
      hotel: ['hotel', hotel1Schema],
      rail: ['rail', rail1Schema],
      tour: ['tour', tourSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
