/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Air2, air2Schema } from './air2.js';
import { Car2, car2Schema } from './car2.js';
import { Hotel2, hotel2Schema } from './hotel2.js';
import { Misc, miscSchema } from './misc.js';
import { Rail2, rail2Schema } from './rail2.js';

export interface Products2 {
  air: Air2;
  car: Car2;
  hotel: Hotel2;
  rail: Rail2;
  misc: Misc;
  additionalProperties?: Record<string, unknown>;
}

export const products2Schema: Schema<Products2> = lazy(() =>
  typedExpandoObject(
    {
      air: ['air', air2Schema],
      car: ['car', car2Schema],
      hotel: ['hotel', hotel2Schema],
      rail: ['rail', rail2Schema],
      misc: ['misc', miscSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
