/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Air16, air16Schema } from './air16.js';
import { Car16, car16Schema } from './car16.js';
import { Hotel16, hotel16Schema } from './hotel16.js';
import { Misc10, misc10Schema } from './misc10.js';
import { Rail16, rail16Schema } from './rail16.js';

export interface Products16 {
  air: Air16;
  car: Car16;
  hotel?: Hotel16;
  rail: Rail16;
  misc?: Misc10;
  additionalProperties?: Record<string, unknown>;
}

export const products16Schema: Schema<Products16> = lazy(() =>
  typedExpandoObject(
    {
      air: ['air', air16Schema],
      car: ['car', car16Schema],
      hotel: ['hotel', optional(hotel16Schema)],
      rail: ['rail', rail16Schema],
      misc: ['misc', optional(misc10Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
