/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Air, airSchema } from './air.js';
import { Car, carSchema } from './car.js';
import { CruiseFerry, cruiseFerrySchema } from './cruiseFerry.js';
import { Hotel, hotelSchema } from './hotel.js';
import { Misc, miscSchema } from './misc.js';
import { Rail, railSchema } from './rail.js';
import { Tour, tourSchema } from './tour.js';

export interface Products {
  air: Air;
  car: Car;
  hotel: Hotel;
  rail: Rail;
  misc?: Misc;
  cruiseFerry?: CruiseFerry;
  tour?: Tour;
  additionalProperties?: Record<string, unknown>;
}

export const productsSchema: Schema<Products> = lazy(() =>
  typedExpandoObject(
    {
      air: ['air', airSchema],
      car: ['car', carSchema],
      hotel: ['hotel', hotelSchema],
      rail: ['rail', railSchema],
      misc: ['misc', optional(miscSchema)],
      cruiseFerry: ['cruiseFerry', optional(cruiseFerrySchema)],
      tour: ['tour', optional(tourSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
