/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Ticket33, ticket33Schema } from './ticket33.js';

export interface Rail16 {
  tickets: Ticket33[];
  additionalProperties?: Record<string, unknown>;
}

export const rail16Schema: Schema<Rail16> = lazy(() =>
  typedExpandoObject(
    { tickets: ['tickets', array(ticket33Schema)] },
    'additionalProperties',
    optional(unknown())
  )
);
