/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Ticket1, ticket1Schema } from './ticket1.js';

export interface Rail {
  id: string;
  tickets: Ticket1[];
  additionalProperties?: Record<string, unknown>;
}

export const railSchema: Schema<Rail> = lazy(() =>
  typedExpandoObject(
    { id: ['id', string()], tickets: ['tickets', array(ticket1Schema)] },
    'additionalProperties',
    optional(unknown())
  )
);
