/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Ticket5, ticket5Schema } from './ticket5.js';

export interface Rail2 {
  id: string;
  tickets: Ticket5[];
  additionalProperties?: Record<string, unknown>;
}

export const rail2Schema: Schema<Rail2> = lazy(() =>
  typedExpandoObject(
    { id: ['id', string()], tickets: ['tickets', array(ticket5Schema)] },
    'additionalProperties',
    optional(unknown())
  )
);
