/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Ticket3, ticket3Schema } from './ticket3.js';

export interface Rail1 {
  id: string;
  tickets: Ticket3[];
  additionalProperties?: Record<string, unknown>;
}

export const rail1Schema: Schema<Rail1> = lazy(() =>
  typedExpandoObject(
    { id: ['id', string()], tickets: ['tickets', array(ticket3Schema)] },
    'additionalProperties',
    optional(unknown())
  )
);
