/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { BaseFare, baseFareSchema } from './baseFare.js';
import {
  EndLocationAddress,
  endLocationAddressSchema,
} from './endLocationAddress.js';

export interface Reservation3 {
  bookingDateTime: string;
  carType: string;
  confirmationNumber: string;
  endDateTime: string;
  endLocationAddress: EndLocationAddress;
  fare: BaseFare;
  isInternational: boolean;
  numberOfNights: number;
  numberOfRooms: number;
  segmentNumber: number;
  startDateTime: string;
  startLocationAddress: EndLocationAddress;
  vendorChainName: string;
  additionalProperties?: Record<string, unknown>;
}

export const reservation3Schema: Schema<Reservation3> = lazy(() =>
  typedExpandoObject(
    {
      bookingDateTime: ['bookingDateTime', string()],
      carType: ['carType', string()],
      confirmationNumber: ['confirmationNumber', string()],
      endDateTime: ['endDateTime', string()],
      endLocationAddress: ['endLocationAddress', endLocationAddressSchema],
      fare: ['fare', baseFareSchema],
      isInternational: ['isInternational', boolean()],
      numberOfNights: ['numberOfNights', number()],
      numberOfRooms: ['numberOfRooms', number()],
      segmentNumber: ['segmentNumber', number()],
      startDateTime: ['startDateTime', string()],
      startLocationAddress: ['startLocationAddress', endLocationAddressSchema],
      vendorChainName: ['vendorChainName', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
