/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Address3, address3Schema } from './address3.js';
import { BaseFare, baseFareSchema } from './baseFare.js';
import { Guest, guestSchema } from './guest.js';

export interface Reservation6 {
  address: Address3;
  bookingDateTime: string;
  checkInDateTime: string;
  checkOutDateTime: string;
  confirmationNumber: string;
  fare?: BaseFare;
  baseFare?: BaseFare;
  guests: Guest[];
  lineItems: string[];
  numberOfNights: number;
  numberOfRooms: number;
  roomType: string;
  segmentNumber: number;
  vendorChainCode: string;
  vendorChainName: string;
  vendorCode: string;
  vendorName: string;
  additionalProperties?: Record<string, unknown>;
}

export const reservation6Schema: Schema<Reservation6> = lazy(() =>
  typedExpandoObject(
    {
      address: ['address', address3Schema],
      bookingDateTime: ['bookingDateTime', string()],
      checkInDateTime: ['checkInDateTime', string()],
      checkOutDateTime: ['checkOutDateTime', string()],
      confirmationNumber: ['confirmationNumber', string()],
      fare: ['fare', optional(baseFareSchema)],
      baseFare: ['baseFare', optional(baseFareSchema)],
      guests: ['guests', array(guestSchema)],
      lineItems: ['lineItems', array(string())],
      numberOfNights: ['numberOfNights', number()],
      numberOfRooms: ['numberOfRooms', number()],
      roomType: ['roomType', string()],
      segmentNumber: ['segmentNumber', number()],
      vendorChainCode: ['vendorChainCode', string()],
      vendorChainName: ['vendorChainName', string()],
      vendorCode: ['vendorCode', string()],
      vendorName: ['vendorName', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
