/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { BaseFare, baseFareSchema } from './baseFare.js';
import {
  DropOffLocation16,
  dropOffLocation16Schema,
} from './dropOffLocation16.js';
import { Fare, fareSchema } from './fare.js';

export interface Reservation56 {
  bookingDateTime: string;
  carType: string;
  confirmationNumber: string;
  dropOffLocation: DropOffLocation16;
  endDateTime: string;
  fare: Fare;
  baseFare: BaseFare;
  isInternational: boolean;
  lineItems: string[];
  numberOfCars: number;
  pickupLocation: DropOffLocation16;
  rentalDays: number;
  segmentNumber: number;
  startDateTime: string;
  vendorChainCode: string;
  vendorChainName: string;
  additionalProperties?: Record<string, unknown>;
}

export const reservation56Schema: Schema<Reservation56> = lazy(() =>
  typedExpandoObject(
    {
      bookingDateTime: ['bookingDateTime', string()],
      carType: ['carType', string()],
      confirmationNumber: ['confirmationNumber', string()],
      dropOffLocation: ['dropOffLocation', dropOffLocation16Schema],
      endDateTime: ['endDateTime', string()],
      fare: ['fare', fareSchema],
      baseFare: ['baseFare', baseFareSchema],
      isInternational: ['isInternational', boolean()],
      lineItems: ['lineItems', array(string())],
      numberOfCars: ['numberOfCars', number()],
      pickupLocation: ['pickupLocation', dropOffLocation16Schema],
      rentalDays: ['rentalDays', number()],
      segmentNumber: ['segmentNumber', number()],
      startDateTime: ['startDateTime', string()],
      vendorChainCode: ['vendorChainCode', string()],
      vendorChainName: ['vendorChainName', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
