/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { BaseFare, baseFareSchema } from './baseFare.js';
import { DropOffLocation, dropOffLocationSchema } from './dropOffLocation.js';
import { Fare, fareSchema } from './fare.js';

export interface Reservation {
  bookingDateTime: string;
  carType: string;
  confirmationNumber: string;
  dropOffLocation: DropOffLocation;
  endDateTime: string;
  fare?: Fare;
  baseFare?: BaseFare;
  isInternational: boolean;
  lineItems: string[];
  numberOfCars: number;
  pickupLocation: DropOffLocation;
  rentalDays: number;
  segmentNumber: number;
  startDateTime: string;
  vendorChainCode: string;
  vendorChainName: string;
  additionalProperties?: Record<string, unknown>;
}

export const reservationSchema: Schema<Reservation> = lazy(() =>
  typedExpandoObject(
    {
      bookingDateTime: ['bookingDateTime', string()],
      carType: ['carType', string()],
      confirmationNumber: ['confirmationNumber', string()],
      dropOffLocation: ['dropOffLocation', dropOffLocationSchema],
      endDateTime: ['endDateTime', string()],
      fare: ['fare', optional(fareSchema)],
      baseFare: ['baseFare', optional(baseFareSchema)],
      isInternational: ['isInternational', boolean()],
      lineItems: ['lineItems', array(string())],
      numberOfCars: ['numberOfCars', number()],
      pickupLocation: ['pickupLocation', dropOffLocationSchema],
      rentalDays: ['rentalDays', number()],
      segmentNumber: ['segmentNumber', number()],
      startDateTime: ['startDateTime', string()],
      vendorChainCode: ['vendorChainCode', string()],
      vendorChainName: ['vendorChainName', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
