/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  DropOffLocation1,
  dropOffLocation1Schema,
} from './dropOffLocation1.js';

export interface Reservation4 {
  bookingDateTime: string;
  carType: string;
  confirmationNumber: string;
  dropOffLocation: DropOffLocation1;
  endDateTime: string;
  isInternational: boolean;
  lineItems: string[];
  numberOfCars: number;
  pickupLocation: DropOffLocation1;
  rentalDays: number;
  segmentNumber: number;
  startDateTime: string;
  vendorChainCode: string;
  vendorChainName: string;
  additionalProperties?: Record<string, unknown>;
}

export const reservation4Schema: Schema<Reservation4> = lazy(() =>
  typedExpandoObject(
    {
      bookingDateTime: ['bookingDateTime', string()],
      carType: ['carType', string()],
      confirmationNumber: ['confirmationNumber', string()],
      dropOffLocation: ['dropOffLocation', dropOffLocation1Schema],
      endDateTime: ['endDateTime', string()],
      isInternational: ['isInternational', boolean()],
      lineItems: ['lineItems', array(string())],
      numberOfCars: ['numberOfCars', number()],
      pickupLocation: ['pickupLocation', dropOffLocation1Schema],
      rentalDays: ['rentalDays', number()],
      segmentNumber: ['segmentNumber', number()],
      startDateTime: ['startDateTime', string()],
      vendorChainCode: ['vendorChainCode', string()],
      vendorChainName: ['vendorChainName', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
