/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Address5, address5Schema } from './address5.js';
import { Fare, fareSchema } from './fare.js';
import { Fare2, fare2Schema } from './fare2.js';
import { Guest, guestSchema } from './guest.js';

export interface Reservation9 {
  address: Address5;
  bookingDateTime: string;
  checkInDateTime: string;
  checkOutDateTime: string;
  confirmationNumber: string;
  fare: Fare2;
  guests: Guest[];
  lineItems: string[];
  numberOfNights: number;
  numberOfRooms: number;
  roomType: string;
  segmentNumber: number;
  vendorChainCode: string;
  vendorChainName: string;
  vendorCode: string;
  vendorName: string;
  baseFare?: Fare;
  additionalProperties?: Record<string, unknown>;
}

export const reservation9Schema: Schema<Reservation9> = lazy(() =>
  typedExpandoObject(
    {
      address: ['address', address5Schema],
      bookingDateTime: ['bookingDateTime', string()],
      checkInDateTime: ['checkInDateTime', string()],
      checkOutDateTime: ['checkOutDateTime', string()],
      confirmationNumber: ['confirmationNumber', string()],
      fare: ['fare', fare2Schema],
      guests: ['guests', array(guestSchema)],
      lineItems: ['lineItems', array(string())],
      numberOfNights: ['numberOfNights', number()],
      numberOfRooms: ['numberOfRooms', number()],
      roomType: ['roomType', string()],
      segmentNumber: ['segmentNumber', number()],
      vendorChainCode: ['vendorChainCode', string()],
      vendorChainName: ['vendorChainName', string()],
      vendorCode: ['vendorCode', string()],
      vendorName: ['vendorName', string()],
      baseFare: ['baseFare', optional(fareSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
