/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { BaseFare, baseFareSchema } from './baseFare.js';

export interface Reservation2 {
  bookingDateTime: string;
  cabin: string;
  confirmationNumber: string;
  endDateTime: string;
  fare: BaseFare;
  linkCode: string;
  segmentNumber: number;
  shipName: string;
  startDateTime: string;
  vendorChainCode: string;
  vendorChainName: string;
  additionalProperties?: Record<string, unknown>;
}

export const reservation2Schema: Schema<Reservation2> = lazy(() =>
  typedExpandoObject(
    {
      bookingDateTime: ['bookingDateTime', string()],
      cabin: ['cabin', string()],
      confirmationNumber: ['confirmationNumber', string()],
      endDateTime: ['endDateTime', string()],
      fare: ['fare', baseFareSchema],
      linkCode: ['linkCode', string()],
      segmentNumber: ['segmentNumber', number()],
      shipName: ['shipName', string()],
      startDateTime: ['startDateTime', string()],
      vendorChainCode: ['vendorChainCode', string()],
      vendorChainName: ['vendorChainName', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
