/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Broker, brokerSchema } from './broker.js';
import { Payment2, payment2Schema } from './payment2.js';
import { Products1, products1Schema } from './products1.js';
import { Seller, sellerSchema } from './seller.js';
import { Taxis3, taxis3Schema } from './taxis3.js';
import { Traveler1, traveler1Schema } from './traveler1.js';

export interface Result1 {
  id: string;
  taxesTotal: number;
  customerName: string;
  globalCustomerNumber: string;
  accountId: string;
  customerNumber: string;
  isInternational: boolean;
  recordLocator: string;
  lastModifiedDateTime: string;
  version: number;
  approvals: string[];
  travelers: Traveler1[];
  brokers: Broker[];
  sellers: Seller[];
  payments: Payment2[];
  taxes: Taxis3[];
  products: Products1;
  additionalProperties?: Record<string, unknown>;
}

export const result1Schema: Schema<Result1> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      taxesTotal: ['taxesTotal', number()],
      customerName: ['customerName', string()],
      globalCustomerNumber: ['globalCustomerNumber', string()],
      accountId: ['accountId', string()],
      customerNumber: ['customerNumber', string()],
      isInternational: ['isInternational', boolean()],
      recordLocator: ['recordLocator', string()],
      lastModifiedDateTime: ['lastModifiedDateTime', string()],
      version: ['version', number()],
      approvals: ['approvals', array(string())],
      travelers: ['travelers', array(traveler1Schema)],
      brokers: ['brokers', array(brokerSchema)],
      sellers: ['sellers', array(sellerSchema)],
      payments: ['payments', array(payment2Schema)],
      taxes: ['taxes', array(taxis3Schema)],
      products: ['products', products1Schema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
