/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Broker16, broker16Schema } from './broker16.js';
import { Payment1, payment1Schema } from './payment1.js';
import { Products16, products16Schema } from './products16.js';
import { Seller16, seller16Schema } from './seller16.js';
import { Taxis1, taxis1Schema } from './taxis1.js';
import { Traveler1, traveler1Schema } from './traveler1.js';

export interface Result16 {
  id: string;
  total: number;
  taxesTotal: number;
  subtotal: number;
  currencyCode: string;
  customerName: string;
  globalCustomerNumber: string;
  accountId: string;
  customerNumber: string;
  isInternational: boolean;
  recordLocator: string;
  lastModifiedDateTime: string;
  version: number;
  approvals: string[];
  travelers: Traveler1[];
  brokers: Broker16[];
  sellers: Seller16[];
  payments: Payment1[];
  taxes: Taxis1[];
  products: Products16;
  additionalProperties?: Record<string, unknown>;
}

export const result16Schema: Schema<Result16> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      total: ['total', number()],
      taxesTotal: ['taxesTotal', number()],
      subtotal: ['subtotal', number()],
      currencyCode: ['currencyCode', string()],
      customerName: ['customerName', string()],
      globalCustomerNumber: ['globalCustomerNumber', string()],
      accountId: ['accountId', string()],
      customerNumber: ['customerNumber', string()],
      isInternational: ['isInternational', boolean()],
      recordLocator: ['recordLocator', string()],
      lastModifiedDateTime: ['lastModifiedDateTime', string()],
      version: ['version', number()],
      approvals: ['approvals', array(string())],
      travelers: ['travelers', array(traveler1Schema)],
      brokers: ['brokers', array(broker16Schema)],
      sellers: ['sellers', array(seller16Schema)],
      payments: ['payments', array(payment1Schema)],
      taxes: ['taxes', array(taxis1Schema)],
      products: ['products', products16Schema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
