/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Filter14, filter14Schema } from './filter14.js';

export interface SearchExpensesbycalculatedTicketStatusRequest {
  limit: number;
  offset: number;
  filter: Filter14;
  additionalProperties?: Record<string, unknown>;
}

export const searchExpensesbycalculatedTicketStatusRequestSchema: Schema<SearchExpensesbycalculatedTicketStatusRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        limit: ['limit', number()],
        offset: ['offset', number()],
        filter: ['filter', filter14Schema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
