/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Filter12, filter12Schema } from './filter12.js';

export interface SearchExpensesbycustomerNumberRequest {
  limit: number;
  offset: number;
  filter: Filter12;
  additionalProperties?: Record<string, unknown>;
}

export const searchExpensesbycustomerNumberRequestSchema: Schema<SearchExpensesbycustomerNumberRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        limit: ['limit', number()],
        offset: ['offset', number()],
        filter: ['filter', filter12Schema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
