/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Filter10, filter10Schema } from './filter10.js';

export interface SearchExpensesbyaccountIdRequest {
  limit: number;
  offset: number;
  filter: Filter10;
  additionalProperties?: Record<string, unknown>;
}

export const searchExpensesbyaccountIdRequestSchema: Schema<SearchExpensesbyaccountIdRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        limit: ['limit', number()],
        offset: ['offset', number()],
        filter: ['filter', filter10Schema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
