/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Filter6, filter6Schema } from './filter6.js';

export interface SearchExpensesbyinvoiceDateTimeRequest {
  limit: number;
  offset: number;
  filter: Filter6;
  additionalProperties?: Record<string, unknown>;
}

export const searchExpensesbyinvoiceDateTimeRequestSchema: Schema<SearchExpensesbyinvoiceDateTimeRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        limit: ['limit', number()],
        offset: ['offset', number()],
        filter: ['filter', filter6Schema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
