/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Filter13, filter13Schema } from './filter13.js';

export interface SearchExpensesbyticketStatusRequest {
  limit: number;
  offset: number;
  filter: Filter13;
  additionalProperties?: Record<string, unknown>;
}

export const searchExpensesbyticketStatusRequestSchema: Schema<SearchExpensesbyticketStatusRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        limit: ['limit', number()],
        offset: ['offset', number()],
        filter: ['filter', filter13Schema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
