/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Result2, result2Schema } from './result2.js';

export interface SearchExpensesbylastModifiedDateTime {
  code: number;
  status: string;
  remainingRecords: number;
  result: Result2[];
  additionalProperties?: Record<string, unknown>;
}

export const searchExpensesbylastModifiedDateTimeSchema: Schema<SearchExpensesbylastModifiedDateTime> = lazy(
  () =>
    typedExpandoObject(
      {
        code: ['code', number()],
        status: ['status', string()],
        remainingRecords: ['remainingRecords', number()],
        result: ['result', array(result2Schema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
