/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Filter15, filter15Schema } from './filter15.js';

export interface SearchExpensesbyhasTransactionRequest {
  limit: number;
  offset: number;
  filter: Filter15;
  additionalProperties?: Record<string, unknown>;
}

export const searchExpensesbyhasTransactionRequestSchema: Schema<SearchExpensesbyhasTransactionRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        limit: ['limit', number()],
        offset: ['offset', number()],
        filter: ['filter', filter15Schema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
