/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Filter3, filter3Schema } from './filter3.js';

export interface SearchExpensesbytravelerEmailRequest {
  limit: number;
  offset: number;
  filter: Filter3;
  additionalProperties?: Record<string, unknown>;
}

export const searchExpensesbytravelerEmailRequestSchema: Schema<SearchExpensesbytravelerEmailRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        limit: ['limit', number()],
        offset: ['offset', number()],
        filter: ['filter', filter3Schema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
