/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Filter2, filter2Schema } from './filter2.js';

export interface SearchExpensesbyinvoiceNumberRequest {
  limit: number;
  offset: number;
  filter: Filter2;
  additionalProperties?: Record<string, unknown>;
}

export const searchExpensesbyinvoiceNumberRequestSchema: Schema<SearchExpensesbyinvoiceNumberRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        limit: ['limit', number()],
        offset: ['offset', number()],
        filter: ['filter', filter2Schema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
