/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Filter, filterSchema } from './filter.js';
import { Sort, sortSchema } from './sort.js';

export interface SearchExpensesRequest {
  limit: number;
  offset: number;
  filter: Filter;
  sort: Sort;
  additionalProperties?: Record<string, unknown>;
}

export const searchExpensesRequestSchema: Schema<SearchExpensesRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        limit: ['limit', number()],
        offset: ['offset', number()],
        filter: ['filter', filterSchema],
        sort: ['sort', sortSchema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
