/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Filter8, filter8Schema } from './filter8.js';

export interface SearchExpensesbylastModifiedDateTimerangeRequest {
  limit: number;
  offset: number;
  filter: Filter8;
  additionalProperties?: Record<string, unknown>;
}

export const searchExpensesbylastModifiedDateTimerangeRequestSchema: Schema<SearchExpensesbylastModifiedDateTimerangeRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        limit: ['limit', number()],
        offset: ['offset', number()],
        filter: ['filter', filter8Schema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
