/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Filter1, filter1Schema } from './filter1.js';

export interface SearchExpensesbyrecordLocatorRequest {
  limit: number;
  offset: number;
  filter: Filter1;
  additionalProperties?: Record<string, unknown>;
}

export const searchExpensesbyrecordLocatorRequestSchema: Schema<SearchExpensesbyrecordLocatorRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        limit: ['limit', number()],
        offset: ['offset', number()],
        filter: ['filter', filter1Schema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
