/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Filter4, filter4Schema } from './filter4.js';

export interface SearchExpensesbybookingDateTimerangeRequest {
  limit: number;
  offset: number;
  filter: Filter4;
  additionalProperties?: Record<string, unknown>;
}

export const searchExpensesbybookingDateTimerangeRequestSchema: Schema<SearchExpensesbybookingDateTimerangeRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        limit: ['limit', number()],
        offset: ['offset', number()],
        filter: ['filter', filter4Schema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
