/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SegmentOption {
  segmentIdRef: number;
  classOfService: string;
  additionalProperties?: Record<string, unknown>;
}

export const segmentOptionSchema: Schema<SegmentOption> = typedExpandoObject(
  {
    segmentIdRef: ['segment_id_ref', number()],
    classOfService: ['class_of_service', string()],
  },
  'additionalProperties',
  optional(unknown())
);
