/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface SegmentOption {
  segmentIdRef: number;
  classOfService: string;
}

export const segmentOptionSchema: Schema<SegmentOption> = object({
  segmentIdRef: ['segment_id_ref', number()],
  classOfService: ['class_of_service', string()],
});
