/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Seller16 {
  name: string;
  additionalProperties?: Record<string, unknown>;
}

export const seller16Schema: Schema<Seller16> = typedExpandoObject(
  { name: ['name', string()] },
  'additionalProperties',
  optional(unknown())
);
