/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Seller {
  name: string;
  validatingCarrier: string;
  additionalProperties?: Record<string, unknown>;
}

export const sellerSchema: Schema<Seller> = typedExpandoObject(
  {
    name: ['name', string()],
    validatingCarrier: ['validatingCarrier', string()],
  },
  'additionalProperties',
  optional(unknown())
);
