/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Sort {
  lastModifiedDateTime: string;
  invoiceDateTime: string;
  additionalProperties?: Record<string, unknown>;
}

export const sortSchema: Schema<Sort> = typedExpandoObject(
  {
    lastModifiedDateTime: ['lastModifiedDateTime', string()],
    invoiceDateTime: ['invoiceDateTime', string()],
  },
  'additionalProperties',
  optional(unknown())
);
