/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface SpecificFlight {
  airlineCode: string;
  flightNumber: string;
}

export const specificFlightSchema: Schema<SpecificFlight> = object({
  airlineCode: ['airline_code', string()],
  flightNumber: ['flight_number', string()],
});
