/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SpecificFlight {
  airlineCode: string;
  flightNumber: string;
  additionalProperties?: Record<string, unknown>;
}

export const specificFlightSchema: Schema<SpecificFlight> = typedExpandoObject(
  {
    airlineCode: ['airline_code', string()],
    flightNumber: ['flight_number', string()],
  },
  'additionalProperties',
  optional(unknown())
);
