/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface StartLocationAddress {
  address1: string;
  address2: string;
  countryCode: string;
  city: string;
  postalCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const startLocationAddressSchema: Schema<StartLocationAddress> = typedExpandoObject(
  {
    address1: ['address1', string()],
    address2: ['address2', string()],
    countryCode: ['countryCode', string()],
    city: ['city', string()],
    postalCode: ['postalCode', string()],
  },
  'additionalProperties',
  optional(unknown())
);
