/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Taxis3Amount, taxis3AmountSchema } from './containers/taxis3Amount.js';

export interface Taxis3 {
  productId: string;
  name?: string;
  code: string;
  amount: Taxis3Amount;
  currencyCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const taxis3Schema: Schema<Taxis3> = lazy(() =>
  typedExpandoObject(
    {
      productId: ['productId', string()],
      name: ['name', optional(string())],
      code: ['code', string()],
      amount: ['amount', taxis3AmountSchema],
      currencyCode: ['currencyCode', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
