/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Taxis1Amount, taxis1AmountSchema } from './containers/taxis1Amount.js';

export interface Taxis1 {
  name: string;
  code: string;
  amount: Taxis1Amount;
  currencyCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const taxis1Schema: Schema<Taxis1> = lazy(() =>
  typedExpandoObject(
    {
      name: ['name', string()],
      code: ['code', string()],
      amount: ['amount', taxis1AmountSchema],
      currencyCode: ['currencyCode', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
