/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Taxis4Amount, taxis4AmountSchema } from './containers/taxis4Amount.js';

export interface Taxis4 {
  name?: string;
  code: string;
  amount: Taxis4Amount;
  currencyCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const taxis4Schema: Schema<Taxis4> = lazy(() =>
  typedExpandoObject(
    {
      name: ['name', optional(string())],
      code: ['code', string()],
      amount: ['amount', taxis4AmountSchema],
      currencyCode: ['currencyCode', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
