/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { TaxisAmount, taxisAmountSchema } from './containers/taxisAmount.js';

export interface Taxis {
  productId: string;
  name: string;
  code: string;
  amount: TaxisAmount;
  currencyCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const taxisSchema: Schema<Taxis> = lazy(() =>
  typedExpandoObject(
    {
      productId: ['productId', string()],
      name: ['name', string()],
      code: ['code', string()],
      amount: ['amount', taxisAmountSchema],
      currencyCode: ['currencyCode', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
