/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Fare, fareSchema } from './fare.js';
import { Leg4, leg4Schema } from './leg4.js';
import { Passenger, passengerSchema } from './passenger.js';

export interface Ticket3 {
  legs: Leg4[];
  recordLocator: string;
  issueDateTime: string;
  bookingDateTime: string;
  fare: Fare;
  payments: string[];
  lineItems: string[];
  passenger: Passenger;
  isInternational: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const ticket3Schema: Schema<Ticket3> = lazy(() =>
  typedExpandoObject(
    {
      legs: ['legs', array(leg4Schema)],
      recordLocator: ['recordLocator', string()],
      issueDateTime: ['issueDateTime', string()],
      bookingDateTime: ['bookingDateTime', string()],
      fare: ['fare', fareSchema],
      payments: ['payments', array(string())],
      lineItems: ['lineItems', array(string())],
      passenger: ['passenger', passengerSchema],
      isInternational: ['isInternational', boolean()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
