/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { BaseFare1, baseFare1Schema } from './baseFare1.js';
import { Leg34, leg34Schema } from './leg34.js';
import { Passenger, passengerSchema } from './passenger.js';

export interface Ticket33 {
  legs: Leg34[];
  recordLocator: string;
  issueDateTime: string;
  bookingDateTime: string;
  fare: BaseFare1;
  payments: string[];
  lineItems: string[];
  passenger: Passenger;
  isInternational: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const ticket33Schema: Schema<Ticket33> = lazy(() =>
  typedExpandoObject(
    {
      legs: ['legs', array(leg34Schema)],
      recordLocator: ['recordLocator', string()],
      issueDateTime: ['issueDateTime', string()],
      bookingDateTime: ['bookingDateTime', string()],
      fare: ['fare', baseFare1Schema],
      payments: ['payments', array(string())],
      lineItems: ['lineItems', array(string())],
      passenger: ['passenger', passengerSchema],
      isInternational: ['isInternational', boolean()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
