/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Fare, fareSchema } from './fare.js';
import { Leg3, leg3Schema } from './leg3.js';
import { Passenger, passengerSchema } from './passenger.js';
import { Payment3, payment3Schema } from './payment3.js';
import { Taxis4, taxis4Schema } from './taxis4.js';

export interface Ticket2 {
  legs: Leg3[];
  invoiceNumber?: string;
  validatingCarrier: string;
  ticketStatus: string;
  calculatedTicketStatus: string;
  taxes: Taxis4[];
  ticketNumber: string;
  recordLocator: string;
  issueDateTime: string;
  bookingDateTime: string;
  fare: Fare;
  payments: Payment3[];
  lineItems: string[];
  bookingType: string;
  passenger: Passenger;
  isInternational: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const ticket2Schema: Schema<Ticket2> = lazy(() =>
  typedExpandoObject(
    {
      legs: ['legs', array(leg3Schema)],
      invoiceNumber: ['invoiceNumber', optional(string())],
      validatingCarrier: ['validatingCarrier', string()],
      ticketStatus: ['ticketStatus', string()],
      calculatedTicketStatus: ['calculatedTicketStatus', string()],
      taxes: ['taxes', array(taxis4Schema)],
      ticketNumber: ['ticketNumber', string()],
      recordLocator: ['recordLocator', string()],
      issueDateTime: ['issueDateTime', string()],
      bookingDateTime: ['bookingDateTime', string()],
      fare: ['fare', fareSchema],
      payments: ['payments', array(payment3Schema)],
      lineItems: ['lineItems', array(string())],
      bookingType: ['bookingType', string()],
      passenger: ['passenger', passengerSchema],
      isInternational: ['isInternational', boolean()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
