/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Ticket4Legs, ticket4LegsSchema } from './containers/ticket4Legs.js';
import { Fare, fareSchema } from './fare.js';
import { Passenger, passengerSchema } from './passenger.js';
import { Payment1, payment1Schema } from './payment1.js';
import { Taxis1, taxis1Schema } from './taxis1.js';

export interface Ticket4 {
  legs: Ticket4Legs[];
  invoiceNumber: string;
  isConjunctive: boolean;
  validatingCarrier: string;
  ticketStatus: string;
  calculatedTicketStatus: string;
  taxes: Taxis1[];
  ticketNumber: string;
  recordLocator?: string;
  issueDateTime: string;
  bookingDateTime: string;
  fare: Fare;
  payments: Payment1[];
  lineItems: string[];
  bookingType: string;
  passenger: Passenger;
  isInternational: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const ticket4Schema: Schema<Ticket4> = lazy(() =>
  typedExpandoObject(
    {
      legs: ['legs', array(ticket4LegsSchema)],
      invoiceNumber: ['invoiceNumber', string()],
      isConjunctive: ['isConjunctive', boolean()],
      validatingCarrier: ['validatingCarrier', string()],
      ticketStatus: ['ticketStatus', string()],
      calculatedTicketStatus: ['calculatedTicketStatus', string()],
      taxes: ['taxes', array(taxis1Schema)],
      ticketNumber: ['ticketNumber', string()],
      recordLocator: ['recordLocator', optional(string())],
      issueDateTime: ['issueDateTime', string()],
      bookingDateTime: ['bookingDateTime', string()],
      fare: ['fare', fareSchema],
      payments: ['payments', array(payment1Schema)],
      lineItems: ['lineItems', array(string())],
      bookingType: ['bookingType', string()],
      passenger: ['passenger', passengerSchema],
      isInternational: ['isInternational', boolean()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
