/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TimeRestriction {
  time: string;
  timeType: string;
  timeWindow: number;
  additionalProperties?: Record<string, unknown>;
}

export const timeRestrictionSchema: Schema<TimeRestriction> = typedExpandoObject(
  {
    time: ['time', string()],
    timeType: ['time_type', string()],
    timeWindow: ['time_window', number()],
  },
  'additionalProperties',
  optional(unknown())
);
