/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema.js';

export interface TimeRestriction {
  time: string;
  timeType: string;
  timeWindow: number;
}

export const timeRestrictionSchema: Schema<TimeRestriction> = object({
  time: ['time', string()],
  timeType: ['time_type', string()],
  timeWindow: ['time_window', number()],
});
