/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Reservation3, reservation3Schema } from './reservation3.js';

export interface Tour {
  id: string;
  reservations: Reservation3[];
  additionalProperties?: Record<string, unknown>;
}

export const tourSchema: Schema<Tour> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      reservations: ['reservations', array(reservation3Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
