/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Passport, passportSchema } from './passport.js';
import { TravelerName, travelerNameSchema } from './travelerName.js';

export interface Traveler4 {
  dateOfBirth: string;
  gender: string;
  travelerEmail: string;
  travelerName: TravelerName;
  passport: Passport;
  tspmTravelerId: string;
  additionalProperties?: Record<string, unknown>;
}

export const traveler4Schema: Schema<Traveler4> = lazy(() =>
  typedExpandoObject(
    {
      dateOfBirth: ['date_of_birth', string()],
      gender: ['gender', string()],
      travelerEmail: ['traveler_email', string()],
      travelerName: ['traveler_name', travelerNameSchema],
      passport: ['passport', passportSchema],
      tspmTravelerId: ['tspm_traveler_id', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
