/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { FfNumber, ffNumberSchema } from './ffNumber.js';

export interface Traveler {
  travelerType: string;
  ffNumbers: FfNumber[];
  additionalProperties?: Record<string, unknown>;
}

export const travelerSchema: Schema<Traveler> = lazy(() =>
  typedExpandoObject(
    {
      travelerType: ['traveler_type', string()],
      ffNumbers: ['ff_numbers', array(ffNumberSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
