/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TravelerName {
  firstName: string;
  lastName: string;
  additionalProperties?: Record<string, unknown>;
}

export const travelerNameSchema: Schema<TravelerName> = typedExpandoObject(
  { firstName: ['first_name', string()], lastName: ['last_name', string()] },
  'additionalProperties',
  optional(unknown())
);
