/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema.js';
import { FfNumber, ffNumberSchema } from './ffNumber.js';

export interface Traveler {
  travelerType: string;
  ffNumbers: FfNumber[];
}

export const travelerSchema: Schema<Traveler> = lazy(() =>
  object({
    travelerType: ['traveler_type', string()],
    ffNumbers: ['ff_numbers', array(ffNumberSchema)],
  })
);
