/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Traveler1 {
  firstName: string;
  lastName: string;
  emailAddress: string;
  identifiers: string[];
  profileStatus: string;
  additionalProperties?: Record<string, unknown>;
}

export const traveler1Schema: Schema<Traveler1> = typedExpandoObject(
  {
    firstName: ['firstName', string()],
    lastName: ['lastName', string()],
    emailAddress: ['emailAddress', string()],
    identifiers: ['identifiers', array(string())],
    profileStatus: ['profileStatus', string()],
  },
  'additionalProperties',
  optional(unknown())
);
