/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { Passport, passportSchema } from './passport.js';
import { TravelerName, travelerNameSchema } from './travelerName.js';

export interface Traveler4 {
  dateOfBirth: string;
  gender: string;
  travelerEmail: string;
  travelerName: TravelerName;
  passport: Passport;
  tspmTravelerId: string;
}

export const traveler4Schema: Schema<Traveler4> = lazy(() =>
  object({
    dateOfBirth: ['date_of_birth', string()],
    gender: ['gender', string()],
    travelerEmail: ['traveler_email', string()],
    travelerName: ['traveler_name', travelerNameSchema],
    passport: ['passport', passportSchema],
    tspmTravelerId: ['tspm_traveler_id', string()],
  })
);
