/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { FfNumber, ffNumberSchema } from './ffNumber.js';
import { TravelerName, travelerNameSchema } from './travelerName.js';

export interface Traveler3 {
  ffNumbers: FfNumber[];
  travelerName: TravelerName;
  additionalProperties?: Record<string, unknown>;
}

export const traveler3Schema: Schema<Traveler3> = lazy(() =>
  typedExpandoObject(
    {
      ffNumbers: ['ff_numbers', array(ffNumberSchema)],
      travelerName: ['traveler_name', travelerNameSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
