/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface TravelerName {
  firstName: string;
  lastName: string;
}

export const travelerNameSchema: Schema<TravelerName> = object({
  firstName: ['first_name', string()],
  lastName: ['last_name', string()],
});
