/**
 * ASB APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { FfNumber, ffNumberSchema } from './ffNumber.js';
import { TravelerName, travelerNameSchema } from './travelerName.js';

export interface Traveler3 {
  ffNumbers: FfNumber[];
  travelerName: TravelerName;
}

export const traveler3Schema: Schema<Traveler3> = lazy(() =>
  object({
    ffNumbers: ['ff_numbers', array(ffNumberSchema)],
    travelerName: ['traveler_name', travelerNameSchema],
  })
);
