/**
 * BCD Travel APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  accessTokenAuthenticationProvider,
  basicAuthenticationProvider,
  compositeAuthenticationProvider,
} from './authentication.js';
import { Configuration } from './configuration.js';

export function createAuthProviderFromConfig(config: Partial<Configuration>) {
  const authConfig = {
    bearer:
      config.bearerCredentials &&
      accessTokenAuthenticationProvider(config.bearerCredentials),
    basic:
      config.basicCredentials &&
      basicAuthenticationProvider(
        config.basicCredentials.username,
        config.basicCredentials.password
      ),
  };

  return compositeAuthenticationProvider<
    keyof typeof authConfig,
    typeof authConfig
  >(authConfig);
}
